### ISSUE TITLE
multiple split options

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#10]
we need to build in the capacity for the user to split based on multiple categorizations
need to create the factor set up and have the functions modularized appropriately for this to work right

**Comment by mhuso** [comment]
I'm not sure this is necessary, and definitely of low priority. The program runs fairly rapidly, so that if the user has two splits, then they can just run sequentially. What I think we need to add is a table of results, not just a graph. I'll add an issue for this...

**Comment by DAPPERstats** [comment]
ok! noted that this isn't really any issue. let's close this then for the time being.
