### ISSUE TITLE
Detection Probability not calculating / button inactive

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#103]
I have tried a variety of inputs but was unable to get Detection Probability to calculate.  (I asked Dan about this and he said it had worked in a previous version, so I will submit it here).  Here are the settings I used:

1. Data Input:  (All the example files)
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = Search1, Search2, Search3, Search4
                                                       Predictor Variables = Visibility, Fix k = No
4. Run Searcher Efficiency Model (Selected model is p ~ 1; k ~ 1) for all cases S/L/M/XL)
5. Analyses > Carcass Persistence: Last Time Present = LastPresentDecimalDays, 
                                                       First Time Absent = FirstAbsentDecimalDays,
                                                       Predictor Variables = Season, Distributions = (All)
6. Run Carcass Persistence Model (Selected model is dist: wiebull; l ~ Season; s ~ Season for all cases S/L/M/XL)
7. Analyses > Detection Probability: Estimate Detection Probability

The Estimate Detection Probability button is available to click, and it highlights when I roll over it.  When I click the Estimate Detection Probability button, it appears to click (darkens on mouse input) but nothing happens.  There is no "running model" box in the bottom right of the app, and I don't see a spike in CPU usage.  No errors or warnings were generated in the console, so perhaps the button simply became un-linked from what it previously operated.

**Comment by DAPPERstats** [comment]
this isn't an issue. as i mentioned in the meeting yesterday and to @ddalthorp in an email, the button doesn't do anything right now, and it won't until the code for detection probability is updated.
