### ISSUE TITLE
fixing k at 0 rather than 1?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#104]
User needs to have responsibility for k without us making a decision by default, especially in the case where there is just one column in the SE trials. Throw an ERROR and force the user to make a commitment about what to do about k. 

In the bimodal k anomaly, WARNING (perhaps in the form of an asterisk).

**Comment by DAPPERstats** [comment]
k is now fixed at 0 not 1 (it should be throughout, if there are places where it's not, let me know)

if there's just one SE trial, the choice of k doesn't inherently matter

**Comment by DAPPERstats** [comment]
can you pull the bimodal warning out to a different issue please? it's helpful to keep the issues on a single task or set of very related tasks (all on inputs or all on outputs). thanks!

**Comment by ddalthorp** [comment]
k should definitely not be fixed at 0, or at 1. This should be a user choice.

k is a key component of the estimator for g, whether or not the user has sufficient data for properly estimating it. In the case of insufficient data, it is important to give the user the responsibility for making a the decision about what to do about it rather than us giving a default k = 0 or k = 1. 

This especially in the case where there is just one column in the SE trials. Throw an ERROR and force the user to make a commitment about what to do about k.

**Comment by DAPPERstats** [comment]
what limits do we need on the values the user can input for k? right now, it can't be less than 0 or greater than 1.

**Comment by ddalthorp** [comment]
k in [0, 1].

Yes, although the primary purpose of the software is mortality estimation, looking at SE and/or CP by themselves is certainly possible. If someone wants to just estimate p for one search and not estimate g for any purpose, they can just enter a fixed value (GUI side). That's something we could include as something like a footnote in the user guide...that a value for k is required. 

Alternatively, a radio button or separate button for estimating p in isolation could be added GUI-side. Then, flag the returned model with k = NA so that it cannot be used in estimation of g. 

On the command-line side, if only one column is entered as data, there should be no need to enter anything for k, and they can model p to their hearts' content, but the resulting pkmodel object should have NA for k so it could not be used in estimation of g's or M's.

**Comment by DAPPERstats** [comment]
the issues associated with k fixing and such have all been handled through the recent set of PRs (#106 #107 #108 #109 )

note that now that k is explicitly not estimated when there's only one observation, and the resulting output is empty accordingly for k. to accommodate downstream and behind the scene needs, `rpk` now has a `kFill` argument that fills the missing k values if need. that is, you can still get a simulated set of p values, just with `NA` for k under the default settings with only one observation.
