### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#11]
across the board, we need to build in error checking
we want the GUI to be able to run without breaking...it should spit back messages that make sense to a general user. this will translate well into command line error and warning messages.

**Comment by DAPPERstats** [comment]
a likely way to present errors and warnings to users in a controlled and clean fashion: https://gallery.shinyapps.io/116-notifications/

**Comment by DAPPERstats** [comment]
another option https://shiny.rstudio.com/articles/validation.html

**Comment by mhuso** [comment]
Below I copy the error checking module for DS729. Some of these checks might be useful for us. It serves as an initial list of things we ran into and wanted to make sure we checked before getting too far into the estimation process, and might give us a first pass at things we want to consider for GenEst.

#Create Error Checks ###############################################################################

Data.Error.Check.Col.Names<-function(Cas, CP, SE, coef.list.SE, coef.list.CP){
	

	# Check to make sure that the interval between searches >0
	check.int <- sum(Cas[,"Interval"]<=0)
	if(check.int >0)
		return(list(Err = 1, 
		message ="Fatality data date of previous search >= search date.  Check dates."))

	# Check to make sure that response variable has only 2 levels, and can be recoded to 0,1
	check.levels.SE.resp <- length(unique(SE[,response.col.SE]))
	if(check.levels.SE.resp > 2)
		return(list(Err = 1, 
		message ="SE response variable has >2 values. Check spelling and case sensitivity."))

	# Check to make sure that explanatory variables selected for use in adjusting
	# observed casualties exist in the searcher efficiency and carcass persistence data
	check.covariates.match.SE<-sum(coef.list.SE%in%names(Cas)==0)
	if(check.covariates.match.SE>0)
		return(list(Err = 1, 
		message ="Fatality data does not contain explanatory variables indicated by searcher efficiency data. Check for spelling errors and case sensitivity."))

	check.covariates.match.CP<-sum(coef.list.CP%in%names(Cas)==0)
	if(check.covariates.match.CP>0)
		return(list(Err = 1, 
		message ="Fatality data does not contain explanatory variables indicated by carcass persistence data. Check for spelling errors and case sensitivity."))
    		
	#check that there are no missing values in fatality data for chosen SEcovariate 
	check.miss.SE <- 0
	if(!identical(coef.list.SE,NA)){
	check.miss.SE1 <-  sum(is.na(Cas[,coef.list.SE]))
	check.miss.SE2 <-  nrow(Cas[which(Cas[,coef.list.SE]==""),])
	check.miss.SE <- check.miss.SE1+check.miss.SE2}
	if(check.miss.SE>0)
		return(list(Err=1,
		message="Covariate variable has missing value in fatality data"))
	
	#check that there are no missing values in fatality data for chosen CPcovariate 
	check.miss.CP <- 0
	if(!identical(coef.list.CP,NA)){
	check.miss.CP1 <-  sum(is.na(Cas[,coef.list.CP]))
	check.miss.CP2 <-  nrow(Cas[which(Cas[,coef.list.CP]==""),])
	check.miss.CP <- check.miss.CP1+check.miss.CP2}
	if(check.miss.CP>0)
		return(list(Err=1,
		message="Covariate variable has missing value in fatality data"))

	#### run these two lines after all the separate error checks
	Err <- list(Err = 0)
  	Err
} # ends Data.Error.Check.Col.Names


Data.Error.Check.Suff.Data<-function(Cas, CP, SE, coef.list.SE, coef.list.CP){

	## check to make sure that the number of turbines in the study is less than the number of turbines at the site 
	## check number of turbines in the study if greater than = number found in Fatality data
	## check for missing Cas turbine IDs
	## check for missing CP Censoring Type values
	## check for missing Cas DWP values
	## check that DWP is between 0 and 1
	## check that there are not missing values for summary groups
	## check CP left is greater than 0
	## check CP left is less than or equal to CP right
	## check CP left is less than CP right when event code=3 (interval censoring)
	## check CP event codes are 0,1,2,3
	## check to make sure that CP and SE data have at least 10 observations for all combos of
	## covariates, for now this includes all interaction wise combos
	## check to make sure that SE do not have only 0 (not found) data for some combo of covariates
	## Check that if CP has 100% right censored data the values are reasonable relative the interval length


    #Check Nturbines in study is less than Nturbines at site
	if(Num.Turbines.in.Study>Num.Total.Turbines.Site)
		return(list(Err = 1, 
		message =" Total Number of Turbines in the Study should be less than or equal to the Total Number of Turbines at the Site "))
    
    #Check Nturbines in study is greater than how.many.turbines (unique in Cas)
	if(Num.Turbines.in.Study<length(Turbines))
		return(list(Err = 1, 
		message =" Total Number of Turbines in the Study should be greater than or equal to the number of values found in the Fatality data"))    

    #check for missing values in fatality Turbine ID 
	check.miss.ID <- sum(is.na(Cas[,turbine.col]))
	if(check.miss.ID>0)
		return(list(Err = 1,
		message="Missing turbine ID in fatality data"))

    #check for missing values in CP event 
	check.miss.event <- sum(is.na(CP[,event.col]))
	if(check.miss.event>0)
		return(list(Err = 1,
		message="Missing CP Censoring Type value"))

   #check DWP Missing
	if (!identical(propsrch, "Hundred")) {
	check.DWP <- sum(is.na(Cas[,propsrch]))
	if(check.DWP > 0)
		return(list(Err = 1,
		message="Missing DWP value in fatality data"))}

   #check that DWP are between 0 and 1
	if (!identical(propsrch, "Hundred")) {
	if(max(Cas[,propsrch]) > 1)
		return(list(Err = 1,
		message="Fatality DWP values should be between 0 and 1."))
	if(min(Cas[,propsrch]) <= 0)
   		return(list(Err = 1,
		message="Fatality DWP values should be between 0 and 1."))}

    #check that there are no missing values in summary groups
	check.miss.cov <- 0
	if(!identical(summary.list,NA)){
	check.miss.cov1 <-  sum(is.na(Cas[,summary.list]))
	check.miss.cov2 <-  nrow(Cas[which(Cas[,summary.list]==""),])
	check.miss.cov <- check.miss.cov1+check.miss.cov2}
	if(check.miss.cov>0)
		return(list(Err=1,
		message="Fatality summary variable has missing values"))

    #check that CP left values are greater than 0
	check.Left <- sum(is.na(CP[,Left.col]))
	if(check.Left > 0)
		return(list(Err = 1,
		message="Missing CP left column values"))
	if(min(CP[,Left.col])<=0)
		return(list(Err=1,
		message="CP left censored times must be greater than 0"))


    #check that CP right values are always greater than CP left values
	check.Right <- sum(is.na(CP[,Right.col]))
	if(check.Right > 0)
		return(list(Err = 1,
		message="Missing CP right column values"))	
	if(sum(CP[,Left.col] > CP[,Right.col]) >0)
		return(list(Err=1,
		message="CP left censored times must be less than or equal to right censored times"))

    #check that CP right values are strictly greater than CP left values for Event 3	
	if(sum(CP[which(CP[,event.col]==3),Left.col] == CP[which(CP[,event.col]==3),Right.col]) >0)
		return(list(Err=1,
		message="CP left censored times must be less than right censored times for CP trials in which Event=3"))
  
    #check CP event codes are between 0 and 3
	if(max(CP[,event.col]) > 3)
		return(list(Err = 1,
		message="CP Censoring Type values should be 0, 1, 2 or 3."))
	if(min(CP[,event.col]) < 0)
		return(list(Err = 1,
		message="CP Censoring Type values should be 0, 1, 2 or 3."))

    # Check to see if at least 10 of all SE combos 
	SE.combos1<-table(SE[,coef.list.SE]) #will note difference in spacing (should already be gone)
	SE.combos<-as.data.frame(SE.combos1, row.names = NULL,responseName = "Count", stringsAsFactors = TRUE)
	SE.Less.10<-sum(SE.combos$Count<10)
	if(SE.Less.10>0)
		return(list(Err = 1, 
		message ="Not enough searcher efficiency trials at all combinations of covariates (at least 10 of each needed)"))

    # Check to see if at least 10 of all CP combos
	CP.combos1<-table(CP[,coef.list.CP])
	CP.combos<-as.data.frame(CP.combos1, row.names = NULL,responseName = "Count", stringsAsFactors = TRUE)
	CP.Less.10<-sum(CP.combos$Count<10)
	if(CP.Less.10>0)
		return(list(Err = 1, 
		message ="Not enough carcass persistence trials at all combinations of covariates (at least 10 of each needed)"))
    
   # Revised code needs needs to alert user if Fat data contains extra covariate level, otherwise it will just exclude it from total 
   # Check to see if all SE combos needed for Fat are present 
	Cas.SE.combos1 <- table(Cas[,coef.list.SE])
	Cas.SE.combos<-as.data.frame(Cas.SE.combos1, row.names = NULL,responseName = "Count", stringsAsFactors = TRUE)
	if(how.many.SEcovs>1){Cas.SE.Miss<-sum(is.na(merge(Cas.SE.combos,SE.combos, by=coef.list.SE, all.x=T)$Count.y))}
	if(how.many.SEcovs==1){Cas.SE.Miss<-sum(is.na(merge(Cas.SE.combos,SE.combos, by="Var1", all.x=T)$Count.y))}
	if(Cas.SE.Miss>0)
		return(list(Err = 1, 
		message ="Missing searcher efficiency trials for all combinations of SE covariates in Fatality data"))

   # Check to see if all CP combos needed for Fat are present 
	Cas.CP.combos1 <- table(Cas[,coef.list.CP])
	Cas.CP.combos<-as.data.frame(Cas.CP.combos1, row.names = NULL,responseName = "Count", stringsAsFactors = TRUE)
	if(how.many.CPcovs>1){Cas.CP.Miss<-sum(is.na(merge(Cas.CP.combos,CP.combos, by=coef.list.CP, all.x=T)$Count.y))}
	if(how.many.CPcovs==1){Cas.CP.Miss<-sum(is.na(merge(Cas.CP.combos,CP.combos, by="Var1", all.x=T)$Count.y))}
	if(Cas.CP.Miss>0)
		return(list(Err = 1, 
		message ="Missing carcass persistence trials for all combinations of CP covariates in Fatality data"))


    # Check to see if all observations in any SE combos are 0
	SE.zeroes1<-table(SE[SE[,response.col.SE]==1,coef.list.SE])
	SE.zeroes <-as.data.frame(SE.zeroes1, row.names = NULL,responseName = "Count", stringsAsFactors = TRUE)
	if(how.many.SEcovs>1){SE.All.0 <- sum(merge(Cas.SE.combos[which(Cas.SE.combos$Count != 0),], SE.zeroes, by=coef.list.SE, all.x=T)$Count.y == 0)}
	if(how.many.SEcovs==1){SE.All.0<-sum(merge(Cas.SE.combos, SE.zeroes, by="Var1", all.x=T)$Count.y == 0)}		
	if(SE.All.0>0 | is.na(SE.All.0) ==T)
		return(list(Err = 1, 
		message ="Some combinations of covariates have all SE=0. Cannot estimate fatality"))

    # Check that if CP has 100% right censored data the values are reasonable relative the interval length
    #1 there must be at % CP trial longer than the max search interval that is > % interval in Fat data
    #2 or >10 CP trials longer than each search interval
    #3 if covariates, each subset (with right censored data only) must pass the above conditions 
	CP.zeroes <- 0
	if(sum(CP[,event.col])==0 & if.CPcovs==F){
		tab <- as.data.frame(table(Cas[,"Interval"]))
		tab$FatPerc <- table(Cas[,"Interval"])/length(Cas[,"Interval"])
		for (i in 1:nrow(tab)){
		tab[i,"CPCumCount"] <- sum(CP[,Right.col] > as.numeric(as.character(tab[i,1])))
		}
		tab$CPCumPerc <- tab$CPCumCount/length(CP[,Right.col])
		CP.zeroes <- sum(tab$CPCumCount<10 & tab$FatPerc>tab$CPCumPerc)}
	if(sum(CP[,event.col])==0 & if.CPcovs==T){  
		#Check all subsets, data is completely right censored
		tab <- as.data.frame(table(Cas[,"Interval"],Cas[,"CP.Cov.Ind"]))
		tab$FatPerc <- tab$Freq/rep(aggregate(tab$Freq,by=list(tab$Var2),FUN="sum")$x,each=(nrow(tab)/length(unique(tab$Var2))))
		for (i in 1:nrow(tab)){
		tab[i,"CPCumCount"] <- sum(CP[CP$CP.Cov.Ind == tab$Var2[i],Right.col] > as.numeric(as.character(tab$Var1[i])))
		}
		tab <- merge(tab,aggregate(as.data.frame(table(CP[,Right.col],CP[,"CP.Cov.Ind"]))$Freq,by=list(as.data.frame(table(CP[,Right.col],CP[,"CP.Cov.Ind"]))$Var2),FUN="sum"),by.x="Var2",by.y="Group.1")
		tab$CPCumPerc <- tab$CPCumCount/tab$x
		CP.zeroes <- sum(tab$CPCumCount<10 & tab$FatPerc>tab$CPCumPerc)}
	if(sum(CP[,event.col])!=0 & if.CPcovs==T & sum(colSums(table(CP[,event.col],CP[,"CP.Cov.Ind"],exclude = c(0)))==0)>0){  
		#Check certain subsets that have only right censored
		tab <- as.data.frame(table(Cas[,"Interval"],Cas[,"CP.Cov.Ind"]))
		exclude <- as.data.frame(colSums(table(CP[,event.col],CP[,"CP.Cov.Ind"],exclude = c(0)))); names(exclude) <- c("ind");exclude$names <- names(colSums(table(CP[,event.col],CP[,"CP.Cov.Ind"],exclude = c(0))))
		tab <- merge(tab,exclude, by.y="names", by.x="Var2")
		tab$FatPerc <- tab$Freq/rep(aggregate(tab$Freq,by=list(tab$Var2),FUN="sum")$x,each=(nrow(tab)/length(unique(tab$Var2))))
		for (i in 1:nrow(tab)){
		tab[i,"CPCumCount"] <- sum(CP[CP$CP.Cov.Ind == tab$Var2[i],Right.col] > as.numeric(as.character(tab$Var1[i])))
		}
		tab <- merge(tab,aggregate(as.data.frame(table(CP[,Right.col],CP[,"CP.Cov.Ind"]))$Freq,by=list(as.data.frame(table(CP[,Right.col],CP[,"CP.Cov.Ind"]))$Var2),FUN="sum"),by.x="Var2",by.y="Group.1")
		tab$CPCumPerc <- tab$CPCumCount/tab$x
		CP.zeroes <- sum(tab[tab$ind==0,]$CPCumCount<10 & tab[tab$ind==0,]$FatPerc>tab[tab$ind==0,]$CPCumPerc)}
	if(CP.zeroes>0)
		return(list(Err = 1, 
		message ="The CP data is completely right censored or completely right censored for a covariate combination, there is insufficient data to estimate CP for each search interval in the fatality data. Cannot estimate fatality"))		


	#### run these two lines after all the separate error checks
	Err <- list(Err = 0)
  	Err
} # ends Data.Error.Check.Suff.Data

**Comment by DAPPERstats** [comment]
new version of the se models and the gui include robust error checking and message returns rather than errors.
there are almost certainly going to be issues where the app breaks, but they're exceedingly rare
