### ISSUE TITLE
pull arrival simulation through rghat

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#121]
currently, `rghat` and `rghatCarcass` just return `ghat` (the simulated detection probability), but need to also return `A` (the simulated arrival dates)

probably easiest/fastest to do this as a list of two vectors from `rghatCarcass` and a list of two matrices from `rghat`

**Comment by DAPPERstats** [comment]
also just an FYI @ddalthorp i'll get on this shortly and push the updated code
i didn't realize we needed the simulated arrival dates for anything else downstream

**Comment by ddalthorp** [comment]
Awesome...and I'll get the initial splits code worked up shortly too. (Slight delay again, though, as we continued our discussion from the morning for a few more hours). 

For splits we'll need Aj, Mtilde and Mhat (along with the carcass search file and masterSearchSchedule, including possible covariates for splits).  

Aj, Mtilde, Mhat as ncarcass x nsim arrays would be ideal.

**Comment by DAPPERstats** [comment]
this was done earlier, but now A, Mtilde and Mhat are all available as of v 0.0.3.17. Note that A is used (rather than Aj) for names, as there is not a index j on the vector (i.e. it's not a vector of counts, as would be expected for Aj, given the notation used elsewhere)

**Comment by DAPPERstats** [comment]
done w v 0.0.5.0 and beyond
