### ISSUE TITLE
distinguish theoretical g from realized g 

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#122]
estimate detection probability tab: present a theoretical, simplified, and not-sensitive to sample size estimate for g 

estimate mortality tab: calculate the realized g behind the scene of the realized m

**Comment by DAPPERstats** [comment]
@ddalthorp what do we need in terms of the theoretical g functions?

**Comment by ddalthorp** [comment]
The function would be the gvec(days, CPab, persdist, seef) from long ago. CPab and seef would be subsetted for appropriate cells and days = I * 0:20, where I is the selected search interval = median(search interval) as default, with option to enter a different I. nsearch = 20 is long enough to converge reasonably closely to the steady-state balance in most cases but is not so long that it takes forever to calculate. gvec calls ppersist, but it may be expecting a particular format for the return value(?)

When there are regular search interval (like we'll have), there's plenty of room for speeding this code up substantially, and I already have it coded somewhere. At the least, it'll take finding it and doing a little reworking of formatting (an hour or two), but it may also need a little better robustification (another hour or two). I'm not sure I can get around to it within the next few days. Easiest would be to use gvec as-is and put off further optimizing until later.

**Comment by DAPPERstats** [comment]
generic g is fully integrated into the command line and app capabilities as of v 0.0.5.5 #152
