### ISSUE TITLE
Calculate Detection Probability button sometimes hidden after running CP, SE

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#123]
After running CP and SE, the button to calculate detection probabilities sometimes does not become available.   My app version number is 0.0.3.14 (1ffe7c81).  It appears this is linked to viewing of the selected models.  If I run the analysis without viewing **both** the "Searcher Efficiency > Model Selection" and "Carcass Persistence > Model Selection" tabs, the button "Detection Probability > Model Inputs : Estimate Detection Probability"  will be missing.   Settings used:
 
1. Data Input:  (All the example files)
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = Search1, Search2, Search3, Search4
                                                       Predictor Variables = Visibility, Fix k = No
4. Run Searcher Efficiency Model
                        Model for size class S = p ~ 1; k ~ 1
                        Model for size class L = p ~ 1; k ~ 1
                        Model for size class M = p ~ 1; k ~ Visibility
                        Model for size class XL = p ~ 1; k ~ 1

5. Analyses > Carcass Persistence: Last Time Present = LastPresentDecimalDays, 
                                                       First Time Absent = FirstAbsentDecimalDays,
                                                       Predictor Variables = Season, Distributions = (All)
6. Run Carcass Persistence Model 
                        Model for size class S  = dist: exponential; l ~ Season
                        Model for size class L  = dist: exponential; l ~ 1
                        Model for size class M  = dist: weibull; l ~ 1; s ~ Season
                        Model for size class XL = dist: exponential; l ~ 1
7. Analyses > Detection Probability: Estimate Detection Probability

**Comment by ddalthorp** [comment]
Is that how it should be? No estimation of g until models for both SE and CP are selected?

**Comment by mintzj** [comment]
It could be this is a desirable behavior.  The models appeared to select themselves automatically once I viewed the "Model Selection" panels, though there was no prompt asking me to review them.  If we do not want people to proceed without reviewing their models first, perhaps we should default to showing the "Model Select" tab instead of the "Model Comparison Tables" tab once the calculations finish for for CP or SE.

**Comment by mintzj** [comment]
On a side note, the tab names "Model Tables" and "Model Comparison Tables" are pretty similar.  Perhaps we can use something more distinctive for one of them.

**Comment by DAPPERstats** [comment]
this is the desired behavior. until you select the SE and CP models, you can't estimate detection probability. if you click on the model selection tab, it populates a selection for you (the best-fit model based on AICc), thus overcoming that requirement.
