### ISSUE TITLE
Use of Size Class as predictor causes crash

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#125]
When Size Class Column  = Size, it will result in a crash if size is added as a predictor variable in either carcass persistence or searcher efficiency.   A similar crash will occur if any of the other variables are used for both the Size Class Column, and as a predictor variable.   Settings for Searcher Efficiency:

1. Data Input:  Searcher Efficiency Data File "SearcherEfficiencyData.csv"
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = Search1, Search2, Search3, Search4
                                                          Predictor Variables = Visibility, Size. Fix k = No
4. Run Searcher Efficiency Model 

```
Models with incorrect specification were removed from output.
Warning: Error in $: $ operator is invalid for atomic vectors
Stack trace (innermost first):
    67: table
    66: observeEventHandler [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#259]
     2: shiny::runApp
     1: GenEst::runGenEst
ERROR: [on_request_read] connection reset by peer
```

Settings for Carcass Persistence:
1. Data Input:  Carcass Persistence Data File "CarcassPersistenceData.csv"
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Carcass Persistence: Last Time Present = LastPresentDecimalDays, 
                                                       First Time Absent = FirstAbsentDecimalDays,
                                                       Predictor Variables = Season, Size.  Distributions = (All)
4. Run Carcass Persistence Model 

```
Models with incorrect specification were removed from output.
Warning: Error in $: $ operator is invalid for atomic vectors
Stack trace (innermost first):
    67: table
    66: observeEventHandler [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#588]
     2: shiny::runApp
     1: GenEst::runGenEst
ERROR: [on_request_read] connection reset by peer```

**Comment by DAPPERstats** [comment]
fixed w #126
