### ISSUE TITLE
Single SE trial (can't estimate k)

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#13]
In the situation where there is only one SE trial, there is no information regarding k, so the user MUST fix k and specify the value. The value selected doesn't impact the SE fit (there's not a repeat visit, so the likelihood isn't effected by k), but does impact the down-the-line use of the SE model.

As of now, there's no prompting or discussion or interaction with the user for this situation. We need to make this seamless, so that having only one observation default treats k as fixed and has the user input the value.

**Comment by mhuso** [comment]
Has this been addressed? The user has the option to fix k.

**Comment by DAPPERstats** [comment]
just built in wrappers to message this out and fix it nominally at 1 
included in the current updates on the "clean-up-se-functions" branch, will we be merged over soon
