### ISSUE TITLE
testing SE

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#136]
I uploaded the data sets ( inst/extdata/) that Jeff pulled together and tried doing SE analysis with SE_trials.csv. 

A few notes:

- [x] I see nowhere to select the "Size" column in the data file

- [x] I see no indication of which size class the (lovely) figs are for (granted, I was not able to tell GenEst what I wanted for a size class)

- [x] it's not clear what the boxes, whiskers, and horizontal bars represent (I'm guessing median, IQR, user-specified CI, and min/max)

**Comment by ddalthorp** [comment]
- [ ] restore examples to pkm.Rd

- [ ] searches columns should allow 0 => carcass present but not found, 1 => carcass found, and anything else => not searched, and not require the non-searched days to be NA.

- [ ] give CI level for which the "upper" and "lower" intervals are given. 

- [ ] display the columns in $cellwiseTable (pkm.print) with brackets around numbers in the CI's and stat-English in the column names: cell, p_median, 95% CI, k_median, 95% CI. Rows like 
`D.Fall      0.356   [0.245, 0.456]   0.654  [0.567, 0.789]

**Comment by ddalthorp** [comment]
- [ ] `Error in pkm(p ~ Visibility * Season, data = pkdat[pkdat$Size == "small",  : 
  No formula or fixed value provided for k. Provide one.
` ...Change to warning that no k is provided and tag the result to indicate "no K" so not allowed in estimation of g. A use for a "no k" model might be to look at how p changes with search occasion but not constrain it to a k-model. This would be a research or curiosity question rather than an M-estimation question, though, and we should require an estimate or decision about k before fitting models for g.

- [ ] if all carcasses are recovered on first search in a cell, we may need to abort the modeling and use something like p = 1 or [best] p ~ beta(n + 0.5, 0.5) with k fixed at 1. Fit other data on cellwise basis.

**Comment by ddalthorp** [comment]
- [ ] `cpm` with kFixed = 1 returns k estimated to be 0.73 for $Size = "lrg" and p ~ Visibility in Jeff's data set. Should return k = 1. (Also, I'm skeptical of the high AICc for this model).

**Comment by DAPPERstats** [comment]
is this about the command line or the GUI?

on the command line,  you'll want to use pkmSetSize to run analyses in batch across size classes 

in the GUI, size is selectable on the general inputs tab 
![image](https://user-images.githubusercontent.com/23511502/39468011-cb3437f2-4ce5-11e8-8c9e-39e40268ccdc.png)
the size of carcass in any model output is selectable using the "table and figure selection" dropdown on the left panel
![image](https://user-images.githubusercontent.com/23511502/39468035-f31b0430-4ce5-11e8-8317-2c81d109f495.png)
yes that's what the boxes and whiskers mean. it'll be explained in the user guide, but do we want a little text or something here?

**Comment by DAPPERstats** [comment]
the examples were pulled out from the help files associated with cleaning up the package's data files and the runtimes of compilation (we need to install more ## don't run tags). can you format the pkdata set as the other data sets are?

**Comment by DAPPERstats** [comment]
if there's no k formula and there's no fixed k value, what should k be fixed at for estimation?

**Comment by ddalthorp** [comment]
- [ ] if a "Size" column is selected in General Inputs, do not offer it as an option for covariates in CP and SE modeling.

**Comment by ddalthorp** [comment]
"if there's no k formula and there's no fixed k value, what should k be fixed at for estimation?"

On the command-line side, if there is more than one search occasion and no k is selected, the model is fit for p alone for each search interval separately. Then show p as a function of search occasion without regard to k. 

This analysis would not be used for estimation of g.

**Comment by ddalthorp** [comment]
"the examples were pulled out from the help files associated with cleaning up the package's data files and the runtimes of compilation (we need to install more ## don't run tags). can you format the pkdata set as the other data sets are?"

The format of the pk data sets has not changed since that pkmdat...at least not as far as I can tell.

**Comment by ddalthorp** [comment]
"yes that's what the boxes and whiskers mean. it'll be explained in the user guide, but do we want a little text or something here?"

Yes.

**Comment by ddalthorp** [comment]
"the size of carcass in any model output is selectable using the "table and figure selection" dropdown on the left panel"

it might be nice to see the size referenced in the figs (in addition to model & cells). And at some point, we'll need a "print" or "save" option for figs.

**Comment by DAPPERstats** [comment]
size labels and explanatory boxplots added to figures w  v0.0.5.10 #166

**Comment by DAPPERstats** [comment]
table outputs are reformatted w v 0.0.5.11 #171

**Comment by DAPPERstats** [comment]
scale issue with fixed k addressed w v 0.0.5.13 #173

**Comment by DAPPERstats** [comment]
I'm closing this issue and bringing the remaining tasks out to their own issues, including condensing with some other existing tasks and issues.
@ddalthorp can you look at the issues that are up and mark them with milestones as to whether they're needed for release 1 or not?
