### ISSUE TITLE
App running, devtools install did not work.

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#144]
Good news, I was able to get the app to run (version 0.0.5.0, bdf015d), but I couldn't get to it install with Devtools.  What I ended up doing was opening a GitHub linked project and running clean and build.  

```
> devtools::install_github("ddalthorp/GenEst")
Downloading GitHub repo ddalthorp/GenEst@master
from URL https://api.github.com/repos/ddalthorp/GenEst/zipball/master
Error: running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1
```

**Comment by ddalthorp** [comment]
Yeah, devtools and C++ source code seem to be a tricky mix for Windows.  We've been putting Windows binaries in the auxilliary_code folder. These you should be able to install without a problem after downloading and doing "install from local...".

**Comment by DAPPERstats** [comment]
details of the options are more clearly laid out now in the readme as of v 0.0.5.7 #157
