### ISSUE TITLE
dwp

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#150]
We need to xtilde-ize the dwp adjustment. There are several possibilities for doing this. Update later this afternoon...

If dwp is fixed and known for each unit, then the adjustment is relatively straightforward, and we should be able to easily implement the change.

If dwp is estimated from data via distance modeling, it is trickier. Joe found a new source of variation that apparently needs to be accounted for in a two-step process. This is an issue that we can shelve for the moment since we are not quite ready for incorporating a distance modeling module.

**Comment by ddalthorp** [comment]
The simplest accurate adjustment for dwp is carcass-wise (in the usual way): 
`(rcbinom(length(ghat), 1/(ghat * dwp), ghat * dwp)) - (Ecbinom(ghat * dwp) - 1))/(ghat * dwp)`

Then, splits would be done on the resulting Mhat array in the usual way.

**Comment by DAPPERstats** [comment]
this is already accomplished by `DWPbyCarcass` and then `rMhat` or `rMtilde` and `calcMhat` in sequence... right?

**Comment by DAPPERstats** [comment]
yeah, this is accomplished for a fixed DWP for now and there's an existing issue for the non-fixed DWP analysis (#14), so I'm going to close this and suggest that points re: the non-fixed analysis should be put on that issue.

**Comment by ddalthorp** [comment]
It wasn't working in the "rudimentary vignette" in the "workthrough" branch.
