### ISSUE TITLE
DWPbyCarcass

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#160]
does it work if there is only a single size? Or is there an alternative?

Most straightforward would be something like:
`DWP_data$DWP_bat[match(rownames(Aj), DWP_data$unit)]`

**Comment by DAPPERstats** [comment]
it works whether there's a size class/size class column entered or not

**Comment by ddalthorp** [comment]
**Error in DWPbyCarc[carci] <- data_DWPtall[which(matchBoth), "DWP"] : 
  replacement has length zero**

**Comment by DAPPERstats** [comment]
what data and arguments are you passing it?

**Comment by DAPPERstats** [comment]
ah, there was an issue with factors in place of characters. it's fixed now and i've updated your vignette
note that i also replaced your raw calculation of Mhat with that generated by the `rMhat` function, which does what you had written out, but under the hood of a function 

ref: v 0.0.5.14 #180

**Comment by ddalthorp** [comment]
factors vs. characters is an ongoing issue. The primary difficulty is how subsetting is handled. If `is.factor(size)`, then the subsetted data frame `dat[dat$size == "bat", ]` contains residual info about the previous, unsubsetted state of the data that can cause problems your code assumes that the data are clean.

I like to read in character strings as character strings and store them as character strings in their data frames and lists.

**Comment by DAPPERstats** [comment]
yeah, it's a result of R and reading in stringsAsFactors
if you see other spots where this is causing a problem, let me know
