### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#17]
Given what our products are planned to be, we should start working to document the code and the app and the math in a way that helps us track progress and gets us on our way to producing necessary products. 

The Code Flow doc was the beginning version of documenting the code here, but I think we need to start building out the documentation as we'll want it for CRAN and a user manual/tutorial with appendices. 

We should also consider what documentation we'll want to develop for ourselves to help record the flow and connection of the code, to help facilitate future version updates, debugging, etc etc.

**Comment by mhuso** [comment]
You've made a great start on this!

**Comment by DAPPERstats** [comment]
start working in roxygen2-based documentation 
http://r-pkgs.had.co.nz/

**Comment by DAPPERstats** [comment]
shifted to standard package documentation for v 0.0.1.1. closing this issue to facilitate more specific issues re documentation.
