### ISSUE TITLE
Handle situation where all carcasses in a cell are found on the first search

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#176]
@ddalthorp's suggestion from #136 
if all carcasses are recovered on first search in a cell, we may need to abort the modeling and use something like p = 1 or [best] p ~ beta(n + 0.5, 0.5) with k fixed at 1. Fit other data on cellwise basis.

**Comment by ddalthorp** [comment]
...or figure out a way to tune Lisa's pk model by fixing bad cells. That seems dodgy.

**Comment by DAPPERstats** [comment]
just circling back on this. @ddalthorp and @madsenl , what's the best way to handle the situation where all carcasses in a cell are found on the first search? and @ddalthorp , can you code that patch up?

**Comment by ddalthorp** [comment]
I think it was already done from the very beginning. The model just returns a non-determinate k that simulates 0 and 1 for k. It works unless no simpler, adequate model is available. The inadequacy of the model is clear in the diagnostic plots, and the user can decide what to do from there.

**Comment by ddalthorp** [comment]
Figuring out all the details of modeling this special case may be more effort than we can afford for beta version. Instead, for now:
- If all are found on the first search in all cells, crash with error message. 
- If all are found on first search in some cells but not others, user will have the option to select a simpler model.
