### ISSUE TITLE
update documentation regarding the solar datasets

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#184]
@mintzj I was able to track down the issues causing the warnings with the solar data sets you added. it turned out that the data objects were actually named the same thing (even though the file names were different) and there wasn't an entry for either in the `R/data.R` script. 
I took care of renaming the data object and adding entries, but the entries are placeholders, so please check and add any additional details.
Please do this by first creating a new branch, then editing in that branch, then creating a Pull Request from that branch. Don't merge the PR, but tag me in it (either in the text or as a reviewer) and I'll make sure everything's good to merge it in.
Thanks!

**Comment by mintzj** [comment]
@DAPPERstats In this file (R/data.R) we would like to have the descriptions written in markdown describing the columns in each simulation file, right?

**Comment by DAPPERstats** [comment]
it's actually in the **roxygen2** formatting style, which is just upstream of markdown (it creates the markdown files). the basic formatting is pretty similar to markdown formatting, but every line needs to start with `#'` 

https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html

**Comment by ddalthorp** [comment]
I've been working on descriptions in roxygen2 for data.R and am getting fairly detailed about the raw mechanics of what the data are. Then, in vignettes, discussing how the data can be used, analyzed, interpreted, etc.

**Comment by DAPPERstats** [comment]
a couple of quick notes about the documentation for the data:

- keep titles for object documentation small (expand on the details in the descriptions). I'm getting the following warning when I run `devtools::document()` to build the documentation:

```
Warning: data.R:182: Section title spans multiple lines: 
@section Density Weighted Proportion (\code{DWP})
```

and in general, titles should be kept to a single line. I would suggest having titles for the data objects that are < 10 words

- double check brackets. i'm getting the following warnings when I run `devtools::document()` to build the documentation:

```
Warning: @section [data.R#70]: mismatched braces or quotes
Warning: @section [data.R#95]: mismatched braces or quotes
Warning: @section [data.R#118]: mismatched braces or quotes
```

**Comment by ddalthorp** [comment]
`@section Density Weighted Proportion (\code{DWP})` is not very long (~chars)...is there some other issue giving the warning?

**Comment by DAPPERstats** [comment]
(which is to say that might be an artifact of the braces issue)

**Comment by mintzj** [comment]
I am trying to track this down what is causing the mismatched braces issue.  @DAPPERstats Thank you for the tip about devtools::document(), I wasn't sure what else needed to be run to check the documentation was working properly.  This seems to be what is.

**Comment by DAPPERstats** [comment]
for sure!
yeah, so my main go-to functions for building stuff locally are

```
devtools::document() #builds all the documentation
devtools::load_all() #just loads the package
devtools::build() #checks source build
devtools::build(binary = TRUE) #checks windows build for me since I'm on windows machine
devtools::build_vignettes() 
devtools::clean_dll() #sometimes needed to tidy the Rcpp code output
```

**Comment by DAPPERstats** [comment]
oh, and another thing that's weird about building the documentation: there are certain things that devtools won't write into an existing `NAMESPACE`, so I tend to delete that file before running `devtools::document()`

**Comment by mintzj** [comment]
One of the (rather sneaky) causes of the "missing quote or braces" appears to be the special characters \ and %.  If we want to insert these characters in documentation we need to use \\ and \% respectively.  Without the escape character the documentation may be generated but the @-section containing the error will be missing.  A warning is generated for the entry _preceding_ the entry with the error (for example, the previous \item in a list).

**Comment by ddalthorp** [comment]
such fun!

**Comment by mintzj** [comment]
I thought it was pretty amusing - another useful one is there is a required colon after @-section \<name>:
Without the colon, the documentation will be created however any sections following the error will be missing.  An error about section titles spanning multiple lines is generated at the end of the documentation page (right after the @-source line).

**Comment by DAPPERstats** [comment]
@mintzj added expanded documentation, addressing this issue in #207
