### ISSUE TITLE
column names in DWP data frame

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#186]
revise requirement so that the column names match the carcass size classes rather than paste0("DWP_", size)

**Comment by DAPPERstats** [comment]
this will need to be accompanied by changes to the column names in all of the data sets

**Comment by ddalthorp** [comment]
don't know if it will _need_ to be, but as a second step that wouldn't be a bad idea

**Comment by DAPPERstats** [comment]
this is done as of v 0.0.5.18 and #190 

in addition to the straight size class based matching (without the "`DWP_`" part), the option now exists to input a specific `DWPCol` for when you only want to use a particular column from `DWP_data` (although note that you can still pass the whole set of DWP data to the function even if you've only got carcasses from a subset of size classes in the DWP table, that's not an issue. there's an error thrown if a size class of a carcass isn't in the DWP table, but not vice-versa). this allows the construction of a generalized value alongside size-specific values quite simply

also, if you have a very simple data set, and you don't bother with the size classes, you just need to have a column that's named `DWP` (not case sensitive) and it will be what gets used.
