### ISSUE TITLE
names in example data

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#188]
...improve consistency and readability (esp. for easy scanning through lists, easy typing, and easy remembering).

Short, simple, consistent names make it easy for a user or developer to scan lists and find what they are looking for. Judicious use of abbreviations for commonly-used terms generally make for easy reading, typing, and remembering.

E.g, within the inst/extdata folders, users will be searching for a general category (wind_, solar_, etc.) first and then specific examples (RP, cleared plots, etc.). Putting the general category first followed by a clear separator before the subspecifier facilitates this kind of reading. 

inst/extdata/
  mock_data [do we still need this?]
  solar_powerTower
  solar_PV
  solar_trough
  wind_cleared
  wind_RP

Within the folders are lists of .csv's. Users will ALWAYS be looking for CO, SS, CP, etc. data, so put those up front in an easily scanable and typable form, followed by an underscore, followed by a subspecifier to uniquely identify the particular (e.g.) CO file:

E.g.:
  CO_RP.csv
  CP_RP.csv
  DWP_RP.csv
  SE_RP.csv
  SS_RP.csv

That format is much easier to scan, type, and remember than:
  carcObsSolarTrough.csv
  carcPersSolarTroughDat.csv
  dwpSolarTrough.csv
  searchEffSolarTroughDat.csv
  searchSchedSolarTroughDat.csv

For the .RData files in data/ folder:
-- do not include "data" or "dat" in the name (`.RData` files stored in `data` directory do not need another  "data" specifier)
-- do include a simple indicator what the general context is, followed by an underscore, followed by a simple subspecifier
-- match folder names in the inst/extdata folder

E.g.:
  mock_data.RData
  solar_powerTower.RData
  solar_PV.RData
  solar_trough.RData
  wind_cleared.RData
  wind_RP.RData

These are imported to an R working session as lists. Within them are data frames with SE, CP, SS, DWP, and CO data. Those are VERY common terms in the app and modeling, so using the abbreviations rather than writing them out is helpful for reading, typing, and remembering.
  SE
  CP
  SS
  DWP
  CO

is much easier to scan with eye, to type, and to remember than:
  SearcherEfficiencyData
  CarcassPersistenceData
  SearchScheduleData
  DensityWeightedProportionData
  CarcassObservationData

**Comment by DAPPERstats** [comment]
This will need to be accompanied by changes to all of the data loading calls in the vignettes

**Comment by ddalthorp** [comment]
yes

**Comment by DAPPERstats** [comment]
existing data sets and the vignettes are updated to this standardized format as of v 0.0.5.18 #190 

i'm closing this issue as the formatting of the existing objects has been updated, but this info will need to be referenced again for any new data sets

**Comment by ddalthorp** [comment]
for .csv's, do append a specifier to the names to avoid orphaning data sets (not needed in the .RData list elements because those are not so easily orphanable by mistake).

**Comment by DAPPERstats** [comment]
specifier suffixes have been added to the .csvs that didnt have them.
will be pushed with v 0.0.6.5 later tonight

**Comment by DAPPERstats** [comment]
PR for 0.0.6.5: #213
