### ISSUE TITLE
smoothen plotting for split fatalities, esp with modest or large numbers of levels

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#189]
when there is just a single split with a handful of levels or two splits with just a few levels each, the fatality plots are sized just fine. however, stuff gets really squished quickly as the number of levels increases.

as an example, @ddalthorp in your vignette, I ended up doing the combination of turbine and season and the figure existed but it wasn't readable (each panel was too tiny).

so, I guess my question is, in the instance where there are two splits (and especially when there are lots of levels within at least one split, but even more than just a few levels results in a ton of boxplots), how do you want things to get produced so you can make comparisons across the levels? 

and when there are two splits, do you still want figures across each main split (ignoring the other) or do you only want it fully parsed?

**Comment by ddalthorp** [comment]
Hmm... 
It would work if the horizontal split were "Turbine" and the vertical split, "Season". 

Originally, I was thinking that I'd put the longer split (in terms of number of levels) along the horizontal axis, but it wasn't clear how to put a temporal split on the vertical. Theoretically, I don't see how it should not be a problem at all. I'll take a look at the code to see if we can do it easily (it seems like it would just be a matter of rearranging the boxes, which shouldn't pose any problems).

**Comment by DAPPERstats** [comment]
the issue with that, however, is that we want the app to only need to be scrollable in one direction: downward (if at all possible, to help users move through it more fluidly). that's why the other figures expand (almost exclusive) downward 

this means i'm enforcing some rather strong width guidelines on the panels, which the `ghatGeneric` estimation pushed just up against, but which the number of units you and jeff put into the data would blow up if unit is used as a split

**Comment by ddalthorp** [comment]
The horizontal splits all go in one fig, so we can probably squeeze a hundred or so (e.g., turbines, search dates) in one panel without the graph looking bad. x-axis labels would be a (slight) problem because we can't print 100 labels on one horizontal axis; however, all the labels and numbers would be available in a table if desired.

**Comment by DAPPERstats** [comment]
i've actually got code that will make that kind of figure label. the first two levels are coded up already (you can see it with the ghatGeneric figure) where it starts normal and then it rotates. the next level would be blocking the axes labels so the grouping is shown without repetition...totally doable, i just haven't coded it up yet. the ideal would be to avoid ever needing a secondary table to interpret the figure. i think we can do it for most sized splits already, and knowing what the range of possible levels of a split (here numbers of units) could be will help make sure i've got code flexible enough at the high end

**Comment by ddalthorp** [comment]
cool.

In looking at the figs with CO splits, I'm thinking in a lot of cases it'd look better if the levels were alphabetized, so we'd get t1, t2, t3, ... instead of, say, t21, t74, t8, 

But, if we just do straight up ordering, we'd get t1, t10, t11, ..., t2, t20,

**Comment by DAPPERstats** [comment]
i think things look pretty good now. additional specific issues can be created to address any lingering concerns for the time being
