### ISSUE TITLE
generalize the crossmodelcells function

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#19]
allow to work with more factor combinations
base flexibility on make_egDat function

**Comment by mhuso** [comment]
This looks exactly the same as #18...

**Comment by DAPPERstats** [comment]
this is basically for the interaction between the SE and CP models, so it's for one level higher than what's referenced in #18. in any case, if we're sticking with max 2 factors for each now, this isn't an issue for us to be concerned with. i'll close it for now and we can re-visit it later if we decide that we want to generalize the models to >2 factors.
