### ISSUE TITLE
x-axis labels for box plots on SE figs (GUI)

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#196]
partially obscured by lines graphs in second row of figs

**Comment by DAPPERstats** [comment]
nm, deleted that comment, i misread and see what you're talking about now

**Comment by DAPPERstats** [comment]
should be addressed in v 0.0.6.5 to be pushed later tonight

**Comment by DAPPERstats** [comment]
PR for 0.0.6.5: #213
