### ISSUE TITLE
SE modeling (GUI)--close error message

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#198]
When a new analysis is run after an error message had been generated on a previous analysis, close the error message.

**Comment by DAPPERstats** [comment]
warnings and errors are being left up so that the user is "forced" (if they want to clear their screen) to interact with the message and close it on their own (there's an 'x' to close the box), as opposed to notifications that are removed when things have run clearly.

**Comment by ddalthorp** [comment]
Users implicitly interact with the message by running a new analysis. If an error or warning is left on the screen after they run a different analysis, it is not clear what the message applies to -- a source of confusion. If you want to "force" the user to close the message by the single method of clicking on the "X", you could disable other calculations until the message is explicitly acknowledged (but that would be irritating too).

**Comment by DAPPERstats** [comment]
fair enough

**Comment by DAPPERstats** [comment]
is included in v0.0.6.5 to be pushed later tonight
