### ISSUE TITLE
Data input--display data

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#199]
In the display table of .csv data that are read in the "Data Input", show all rows as default with vertical scroll bar (if possible) rather than just 10 rows.

**Comment by DAPPERstats** [comment]
it needs to be a restricted number, otherwise rendering large tables into html can grind the app to a halt. we can set the number to more than 10, but it can't be the default to show all rows.

**Comment by ddalthorp** [comment]
OK
