### ISSUE TITLE
value for fixed k

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#200]
Option for entering different fixed k's for different size classes (or fixed for some but not others).

**Comment by DAPPERstats** [comment]
this is going to touch a lot of parts of the code and while definitely do-able, it will take some solid time. unless this is super pressing, I think we should hold on it until after beta.

**Comment by mhuso** [comment]
Once we have k>1 figured out, this might fall into place. For now, I'm ok with a single fixed k for the GUI version.

**Comment by ddalthorp** [comment]
This is not a k>1 issue, but, rather, an issue where p large or p small for one size class (e.g., p = 0.9 for large carcasses so no good data on second search) kills the pk fitting for all size classes because fixed k is required for one class. This was already an issue from one of the beta testers who had zero carcasses found after the first search for large size so was required to use a common fixed k for all classes despite having good data for other sizes.

**Comment by ddalthorp** [comment]
This has been coded on the command-line side for quite some time, but we need mechanism on the GUI side to allow inputting of fixed k by size class.

**Comment by juniperlsimonis** [comment]
full version up and running with v 0.2.15 #562
