### ISSUE TITLE
names rghat, rMhat

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#201]
These are more akin to combining (other) simulated values into estimates of their particular quantity (g or M) as an end in itself rather than generating random deviates from a probability model as the means to another end.

Change names to something simple along the lines of Est_g and Est_M or calcghat and calcMhat (other suggestions?)

**Comment by DAPPERstats** [comment]
done w v 0.0.6.1 #206 and beyond

**Comment by DAPPERstats** [comment]
(changed to estM and estg)
