### ISSUE TITLE
Parameter Documentation for Datasets

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#209]
There was some discussion of recording parameters and key assumptions used in generation of the example datasets in an accessible place at the start of the meeting on Wed. (5/23).  What do you all think is a reasonable place to do this?  I was thinking the corresponding set of assumptions could be linked or referenced to from within the documentation  and vignette for each dataset.  If this is within the manual or some other larger non-R text, we could reference them by (sub)section number.  Another option is it could go within a vignette-like object as misc documentation.

- [x] Wind RP (RP Bat has same assumptions as wind RP)
- [x] Wind Cleared
- [x] Solar PV
- [x] Solar Trough
- [x] Solar powerTower

**Comment by ddalthorp** [comment]
The wind and solar data sets were generated in different ways. Also, the wind world and solar world have a lot of non-intersection, so it makes some sense to have complete descriptions for both. I'm envisioning vignettes for "mock" (showing the rhythm of a command line analysis), wind (discussing details of wind-centric assumptions and analysis), solar (discussing details of solar-centric analysis), and descriptions of the data sets in R/data.R (accessible via, e.g., ?wind_RP). 

Maintaining coherence among the moving pieces is a good goal. 

Maybe separate .Rd files to describe the generation and "meaning" of the data sets w/ hyper-links in the specific help files?

**Comment by DAPPERstats** [comment]
also, if it helps keep things manageable as the documentation grows, everything about the data sets does not all need to be in a single `data.R` file. the documentation just needs to be in a `.R` file within `R/`, so you could totally split the data sets' documentation up into separate files.

**Comment by mintzj** [comment]
I've created a document consolidating relevant information about the solar datasets, however this document ended up being mostly useful to us internally to keep track of what differs between simulated sites and the parameters used in the simulations.  A lot of the information concerning the physical differences between sites and search procedures were contained in the documentation already, so I don't think we will need to add this file into the app documentation, although it could possibly be adapted into a comparison of available datasets.

**Comment by DAPPERstats** [comment]
is there anything remaining to do with the data set documentation, or can this issue be closed, @mintzj and @ddalthorp ?

**Comment by mintzj** [comment]
This is not complete yet,  it's one of the things I wanted to wrap up this week.  I haven't written descriptions for the wind dataset yet but I should be done with it soon.  I'll check it off when I get that done.

**Comment by DAPPERstats** [comment]
also, if possible, @mintzj can you limit the characters per line to 80 in `data.R`?

**Comment by mintzj** [comment]
Sure, I'll take a look over it.  I'm trying to limit to 80 now but something must have slipped by.  There is one area so far I ran into where we shouldn't wrap at 80: the titles of rmd scripts or other rmd headers.  If you break those lines they'll become a new line.
