### ISSUE TITLE
General Inputs

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#21]
Right now we have only the # of iterations to run in the "general Inputs" tab. I suggest either:
1) moving that option to the Fatality Estimation (under Analyses) or
2) moving the credibility level and fraction sampled to the General Inputs section

Either way, change wording of "Fraction of facility surveyed" to "Fraction of sampling units surveyed" or "Fraction of units or area surveyed" or something like that. GenEst can be used to monitor under power lines (no facility) or perhaps even oil spills (length of beach surveyed) etc. so while this value is important, it's hard to come up with a generic term that will fit all situations.

**Comment by DAPPERstats** [comment]
done! will be in the next pushed update.

**Comment by DAPPERstats** [comment]
move fraction sampled back to fatality estimation tab

**Comment by DAPPERstats** [comment]
fraction sampled moved back for v 0.0.1.1
