### ISSUE TITLE
estghat name

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#211]
To estimate g, we calculate ghat. 

To avoid mixing metaphors, let's call our function to estimate g something like `estg` (or `calcghat`).

**Comment by DAPPERstats** [comment]
i've switched over to `estg` for all functions and `g` for all objects as of 0.0.6.5 (will be pushed later tonight)

**Comment by DAPPERstats** [comment]
PR for 0.0.6.5: #213

**Comment by ddalthorp** [comment]
we need hats on the objects...
Our function (`estg` ) is what we use to calculate our estimates, `ghat` object. 

We still don't know g.

**Comment by DAPPERstats** [comment]
noted. i'll swap objects back to `ghat`
