### ISSUE TITLE
language: Estimate "fatality" or "mortality"

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#218]
A "fatality" is a death, an event. 
"Mortality" is rate or number of deaths.

I propose a standard:
1. "estimate mortality" or "estimate the number of fatalities" but not "estimate fatality"
2. in the field, count "carcasses", not "fatalities" (unless we are witnessing the event of a bird getting struck or scorched), and not "mortalities"

Thoughts?

**Comment by DAPPERstats** [comment]
that sounds good

**Comment by DAPPERstats** [comment]
updated in v0.0.6.8 #220
