### ISSUE TITLE
Graphics suggestions

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#23]
All graphs:
    Add legends.
    Remove axis labels from individual graphs. because axes are constant, only need one label at bottom, one on left. Still need tick marks and their values on each graph, just not the labels
    Change colors to black = selected model, grey = full factorial combination model

P and K: annotate with # found/# available at each point, not just single number
             Make box borders lighter
CP:  annotate with initial number available at t=0
Fatality: Find better balance of matrix of graphs depending on # of splits; X axes will have same variable, i.e., fatality, but range may change depending on split. Keep 20 bins for each?

**Comment by DAPPERstats** [comment]
figure updates for everything except the fatality histograms are incorporated in v0.0.0.5
fatality histogram suggestions added to existing issue on that topic.

**Comment by mhuso** [comment]
Nice. Thanks!
