### ISSUE TITLE
Fatality (under Analyses) needs more tabs

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#24]
Can we have tabs in Fatality Estimation, i.e., Data, Figures, Summary Table?
I'd like to be able to see the actual fatality data, just like we can with SE and CP data without going back to the data tab. The figures tab would be the histograms of each split value; the Summary Table is yet to be determined.

**Comment by DAPPERstats** [comment]
done!
will be in the next update i push.
