### ISSUE TITLE
Need sampling fraction input button

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#251]
This is pretty  straightforward for wind, but might be more complicated for solar. For example, the central circle at a PowerTower might be 100% searched, whereas the mirrors in the outer circle are sampled. How can we associate a sampling fraction with each mortality source if there is >1 source at a facility?

**Comment by DAPPERstats** [comment]
the current version of the app has a "fraction of facility surveyed" input on the "mortality estimation" tab. is that not sufficient for our current needs?

**Comment by DAPPERstats** [comment]
also, this appears to be a duplicate of issue #202 unless i'm missing something? what's left on the topic of sampling fractions for the current release?

**Comment by mhuso** [comment]
Oops... yes. I was looking for it on the General Inputs Screen. Sorry!
