### ISSUE TITLE
No models successfully fit

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#254]
It could be this is already under repair but I was not able to successfully fit any models using the wind RP data or the mock data.  

1. Data Input:  (All mock files)
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = Search1, Search2, Search3, Search4
                                                       Predictor Variables = Season, Fix k = No
4. Run Searcher Efficiency Model (Selected model is p ~ 1; k ~ 1) for all cases S/L/M/XL)
5. Analyses > Carcass Persistence: Last Time Present = LastPresentDecimalDays, 
                                                       First Time Absent = FirstAbsentDecimalDays,
                                                       Predictor Variables = Season, Distributions = (All)
6. Run Carcass Persistence Model (Selected model is dist: weibull; l ~ Season; s ~ Season for all cases S/L/M/XL)
7. Analyses > Mortality Estimation: Fraction of Facility Surveyed = 1,
                                                        Units = Unit,
                                                        Date Found = DateFound,
                                                        Date Searched = DateSearched
8. Analyses > Mortality Estimation:  Estimate

Running app version 0.0.8.6 I get a red box in the bottom right stating "No models were successfully fit."

**Comment by ddalthorp** [comment]
This same set works for me running from the command line.

**Comment by DAPPERstats** [comment]
hmm, yeah, i get that now too.
i need to go through the app's server code now that dan's updated some of the code to make sure that the arguments all align and such.

**Comment by DAPPERstats** [comment]
i just ran this at the command line using the `testing_script.R` in `auxillary_code` (which i now realize is misspelled...oops), which is my bread-and-butter test for checking the sequence of calculations behind the app outside of the app to troubleshoot errors.
here's the error thrown:
```
Error in SEsi0(days, pk) : object 'days' not found
```

**Comment by ddalthorp** [comment]
I've got quite a few changes coming...clearing out some bugs and streamlining the interface. it should all integrate well into the existing framework, but the arg lists will be slightly different.

**Comment by DAPPERstats** [comment]
yeah, i figured as much, dan. let me know when you're set on things working at the command line and i'll follow behind to make sure the app still plays nicely.

**Comment by ddalthorp** [comment]
This `Error in SEsi0(days, pk) : object 'days' not found` is from old code. Changes are coming to eliminate these types of errors.

**Comment by mhuso** [comment]
Any updates yet? I'm scheduled to present a talk about GenEst to the Bat-Wind Energy Cooperative Science Advisors on Tuesday. Thanks!

**Comment by DAPPERstats** [comment]
i'm waiting for the go-ahead from @ddalthorp on the code once he's done with it.

**Comment by mhuso** [comment]
Thanks! I'll download it. I wung it for the talk, using your command line vignette, so alles goed!

**Comment by DAPPERstats** [comment]
this should all be addressed as of v 0.0.9.1
