### ISSUE TITLE
CP models: click figures before fitting models

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#275]
When the "figures" tab is clicked before fitting specific models, user sees a blank page with no explanation. Confusing. Give a note to explain what is going on.

**Comment by DAPPERstats** [comment]
what should it say?
and should it be on "figures", "estimates", "model comparison", and "model selection" for both SE and CP?

**Comment by ddalthorp** [comment]
A couple ideas:
-- disable buttons and tabs when they are not usable (this takes work because it requires tracking and toggling of state variables), or
-- move to the empty page but put in a note saying that no models have been fit or selected and direct user how to do it, or
-- instead of moving to a tab with an empty page, stay on originating page with an error message

**Comment by DAPPERstats** [comment]
out of those, the only viable option at this time is the second one with a note. hence my question of what it should say. in the instances that you're talking about, it's just that models haven't been fit yet (not that they haven't been selected), so would a simple message "Models have not been fit yet. Please click the "Run Model" button." suffice? And do you want it on all of the tabs?

**Comment by DAPPERstats** [comment]
explanatory text added on tabs that are present before being populated with output as of v 0.0.9.13 #318
