### ISSUE TITLE
 Mortality estimation: date found drop down

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#279]
disallow ineligible choices of date column

**Comment by DAPPERstats** [comment]
what are the requirements to be eligible?

**Comment by ddalthorp** [comment]
At the very least, the date column needs to contain dates.

**Comment by ddalthorp** [comment]
Check the data in each column in CO. Any columns that contain stuff other than dates cannot be the date found. Do not include them in the drop down list of possibilities.

**Comment by DAPPERstats** [comment]
addressed in v 0.0.9.10 PR #314
