### ISSUE TITLE
CP events -- no left censoring

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#28]
In standard CP field trials, we don't ever encounter left-censored data. The function that parsed CP field data mistakenly assigned an interval of form [0, t2] as event type 2, but it should be event type 3 with left side of interval being 0, BUT 0 is not allowed in a Surv object, so these should be entered as some small positive number instead of 0.

**Comment by ddalthorp** [comment]
Code has been revised.

**Comment by DAPPERstats** [comment]
ah! just found this.
as i mentioned in my comment to the commit, i can edit that in the existing code simply without incurring any additional issues. i'll take care of that and include the updated survival code in v0.0.0.5.
