### ISSUE TITLE
mortality estimation: simple error-checking

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#280]
Instead of "No models were successfully fit" give informative error message when user enters, e.g., 2 for sampling fraction or carcssID for search date. 

E.g., "sampling fraction must be <= 1"

**Comment by DAPPERstats** [comment]
@ddalthorp if you can write up `estM` to throw those errors at the command line, i can pull the messages through to the app notification.

**Comment by juniperlsimonis** [comment]
the sampling fraction issue is handled now with a specific case (#544)
are there other error messages to be specified?
