### ISSUE TITLE
splits figs

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#283]
Include a button to show transposed figs [plot(transposeSplits(...)]

**Comment by DAPPERstats** [comment]
would it be better to just transpose the figure automatically if a particular condition is met? (so the user doesn't even need to know about it)

if so, what criterion would you suggest?

**Comment by ddalthorp** [comment]
The criterion I would use would be for the user to think, "Ya' know? I think this would look better as visibility x season instead of season x visibility." CLICK.

**Comment by DAPPERstats** [comment]
button for transposing the splits is included with v 0.0.11.10 #396
