### ISSUE TITLE
detection probability...not functioning?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#284]
After running through an estimation exercise with wind_cleared, including successful CP, SE, and splits, I get "no models were successfully fit" when I click "Estimate" button in the "Detection probability" tab. 

I see that there are no options available in the "Size class" drop down menu.

**Comment by DAPPERstats** [comment]
i can get that to run properly with the current version (0.0.9.1) that's up on github. what version are you using? if it's that one, can you include all of your inputs to the models so i can try and replicate?

**Comment by ddalthorp** [comment]
0.0.9.1
wind_cleared data
selecting visibility and season for covars on everything
use the #1 model in each case

**Comment by DAPPERstats** [comment]
this should be addressed with v 0.0.9.2 #295 
there was an issue with the function that combines predictors across models not retaining the order of terms for cell names.
