### ISSUE TITLE
plot.pkmSet(): allow easier access to specificModel

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#300]
E.g.,  typing out the full model names is tedious and highly error-prone because formatting must be 100% exact (including spaces etc.)
```
plot(pkmSetObj, specificModel = c(
  "p ~ Visibility; k ~ Visibility + Season",
  "p ~ Visibility; k ~ 1"
))

```
`pkmSetObj` is a list that can be indexed just as easily by number as by name. 
```
plot(pkmSetObj specificModel = c(9, 24))
```
allow either to be used

**Comment by DAPPERstats** [comment]
done as of v 0.0.9.8 w PR #312
