### ISSUE TITLE
No models successfully fit

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#302]
Can't say if this is the same problem we were having before or not, but here's the settings I used.  Warning dialog comes up after SE fitting, no warnings from CP fitting.

Version 0.0.9.3

1. Data Input:  (All the Wind RP files)
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = S1, S2, S3, S4, S5
                                                       Predictor Variables = Visibility, Fix k = No
4. Run Searcher Efficiency Model Selected models:
Model for bat: p ~ 1; k ~ 1
Model for lrg: p ~ 1; k ~ Season
Model for med: p ~ 1; k ~ 1
Model for sml: p ~ 1; k ~ 1

Warning Dialog: Some models were not successfully fit. Failed models were removed.

5. Analyses > Carcass Persistence: Last Time Present = Left, 
                                                       First Time Absent = Right,
                                                       Predictor Variables = Season, Distributions = (All)

6. Run Carcass Persistence Models:
Model for bat: lognormal; l ~ 1; s ~ 1
Model for lrg: weibull; l ~ 1; s ~ 1
Model for med: weibull; l ~ 1; s ~ 1
Model for sml: weibull; l ~ 1; s ~ 1

7. Analyses > Mortality Estimation: Fraction of Facility Surveyed = 1,
                                                        Date Found = DateFound,
8. Analyses > Mortality Estimation:  Estimate

Error Dialog: No models were successfully fit.
No warnings in the R console.

**Comment by DAPPERstats** [comment]
the issue here is that the SE model chosen for the large size class is actually a failed fit for k, but the model still is returned:

```
$cellwiseTable
    cell p_median p_lower p_upper k_median k_lower k_upper
1   fall  0.92062 0.82308 0.96657      NaN     NaN     NaN
2 spring  0.92062 0.82308 0.96657  0.00033       0       1
3 summer  0.92062 0.82308 0.96657  0.99996       0       1
```

what gets caught up during the mortality estimation is that there's an NA value for a k, but then there's no kFill input.

**Comment by DAPPERstats** [comment]
@ddalthorp can you work out a fix for this bug?

**Comment by ddalthorp** [comment]
Mortality estimation should not be allowed if user picks a model without a k.

**Comment by DAPPERstats** [comment]
that's not the problem here. here, the user inputs a k model accordingly, but it fails partially, and returns a partial model rather than a failed model

**Comment by ddalthorp** [comment]
Mortality estimation should not be allowed if user picks a model with a failed k fit.

**Comment by DAPPERstats** [comment]
the model shouldn't be partially returned.

**Comment by ddalthorp** [comment]
Are you sure?

**Comment by DAPPERstats** [comment]
yes

**Comment by ddalthorp** [comment]
what's kFill?

**Comment by DAPPERstats** [comment]
it's used for the edge case where there's no k estimated in the SE model. 

if a user wants to estimate g or M but the SE model doesn't have a k (because there's only one observation, for example), the user needs to fill k with a value.

**Comment by ddalthorp** [comment]
wind_RP data set, large birds, p~ 1, k ~ season:

In fall, all carcasses were found on the first search. The MLE approach does not work in that case. Our solution was to not allow that model and suggest a simpler model, like p ~ 1, k ~ 1. If that doesn't work either, then user should have the option to enter a fixed k (e.g., in a drop down for fixed k, but allowing that to be done by size class rather than require the same fixed k for all size classes). 

This is different from filling in specific blanks with a selected k for a specific cell, which would affect the  estimates in other cells. Lisa and Paul both looked for a way to adjust the likelihood calculations to address the problem, but it turns out to be not quite as easy as it sounds. The edge cases are always a pain in the neck. Our (probably temporary) solution in this case was to require the user to select a simpler model or fix k (for the entire model [for the size], not for select cells). 

A partial model is a failed model. 

Solution: if there are all NAs in the s2 column for a particular cell, return an errored fit.

**Comment by ddalthorp** [comment]
Using my original R6 code, I'm able to get a (bad) fit for the model referenced above. In essence, the fitting says, "I have no idea what k is. Something between 0 and 1." That should be OK too...the pattern should be clear in the diagnostic plots.

**Comment by ddalthorp** [comment]
Remind me...the diagnostic plots are based on the summary data in the cellwise table?

Those statistics are derived from the MLE asymptotics. If those are giving NaN (which they should in this example), you could simply draw boxes extending from zero to 1 with no median, giving an indication that the model has no idea what to do with k. If you simulate from this bad model, k will be 0 about half the time and 1 about half the time (and there will be a warning about the variance matrix not being numerically reliable).

**Comment by ddalthorp** [comment]
I can get the plots from the command line. 

I don't know why they would be crashing in the GUI.

**Comment by DAPPERstats** [comment]
the plots aren't crashing, it's the downstream code of `estM` and `estgGeneric` that are crashing because they're expecting strictly filled numeric values.

**Comment by ddalthorp** [comment]
This is an issue with error-handling and traffic-directing for special cases in SE data. 

Closed. See [https://github.com/ddalthorp/GenEst/issues/357](url) for updates.
