### ISSUE TITLE
package development

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#31]
how do folks feel about using hadley wickham's guide on building R packages as our guiding doc for package development? 
http://r-pkgs.had.co.nz/

he's got lots of experience in producing high quality and high usage packages, so it seems like an obvious choice. 

happy to hear if other folks have templates to follow that would be better.
@studyvin let me know if you've used something else before

**Comment by studyvin** [comment]
@DAPPERstats  I think using Wickham's guide is a good idea. I haven't read the book but I use a lot of his packages.

**Comment by ddalthorp** [comment]
Please, let's do use Wickham's guide. It is well-written, sensible, and gives good common-sense advice. He has some aesthetic ideas that I don't think we should abide (e.g., he avoids upper case letters in variable names and always uses _ instead), but he has his good under-the-hood explanations and explanations for package construction.

**Comment by DAPPERstats** [comment]
alright, i've used wickham's guide for the format and structure for v 0.0.1.1
closing this issue
