### ISSUE TITLE
misaligned column names in solar_trough

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#316]
the CO data have a column named "Unit", the DWP data have a column named "Transect"
those two need the same name in both data sets

**Comment by DAPPERstats** [comment]
while we wait to hear what the specific cause is of that error in `calcSplits`, it works fine to just re-start the builds on travis until you get them to run cleanly.

**Comment by mintzj** [comment]
It seems like Travis keeps re-running them periodically.  Should I merge if I see one passes?

**Comment by DAPPERstats** [comment]
I re-ran some to check them. Travis won't re-start a build unless you tell it.
If stuff's good to be merged it, go for it!
