### ISSUE TITLE
Mortality estimation in GUI

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#329]
Using S:\CRG_Commons\ddalthorp\examples\Example Datasets\Examples 5-19\Wind Example\Datasets\Cleared 60m

Mortality Estimation
a.	No pull-down options for search split
b.	No pull-down options for carcass splits
c.	Error if I choose no splits
![image](https://user-images.githubusercontent.com/30159619/41204321-be1debfe-6c97-11e8-86e9-071a8de1a1d2.png)

**Comment by DAPPERstats** [comment]
what values were used for the inputs on earlier screens?

**Comment by DAPPERstats** [comment]
as of v 0.0.11.1 this does not throw an error
