### ISSUE TITLE
Function documentation

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#33]
The following functions exist in the GenEst package v 0.0.1.1. Currently, they have barebones documentation. Please add to the documentation and check off functions as you complete them.

searcher_efficiency_functions.R
- [ ] pkfunction
- [ ] se_model_fit                    
- [ ] se_model_set_fit             
- [ ] se_model_set_across_sizes_fit       
- [ ] se_theta_create
- [ ] se_aicc_table_create   
- [ ] create_se_figure 

carcass_persistence_functions.R
- [ ] cp_model_fit    
- [ ] cp_model_set_fit                  
- [ ] cp_model_set_across_sizes_fit       
- [ ] cp_theta_create                     
- [ ] cp_aicc_table_create    
- [ ] create_cp_figure   

detection_probability_functions.R
- [ ] create_ss_vec                       
- [ ] probability_persist_to_detection    
- [ ] estimate_g                      
- [ ] estimate_g_across_sizes      
- [ ] create_g_table  
   
fatality_functions.R
- [ ] create_DWP_table   
- [ ] estimate_mhat        
- [ ] condense_mhat              
- [ ] create_mhat_figure                  
- [ ] create_mhat_table               

app_functions.R
- [ ] create_ss_table
- [ ] order_cp_models                 
- [ ] order_se_models                     
- [ ] runGenEst        

utility_functions.R
- [ ] alogit
- [ ] logit  
- [ ] combine_factors                 
- [ ] combine_factors_across_models    
- [ ] model_namer                
- [ ] model_name_reverser

**Comment by DAPPERstats** [comment]
@ddalthorp when you add functions in the code, can you add them to the list here (by editing the original post)? and when the documentation is complete, please check them off.

**Comment by ddalthorp** [comment]
I love this page. Maybe you can show us all how to do this at our meeting on Tuesday.

**Comment by DAPPERstats** [comment]
you just need to edit the original post...all you need to do is click on the pencil and follow the formatting that's present.

**Comment by DAPPERstats** [comment]
closing this issue as functions are being re-written and re-configured. v 0.0.3.0 should have full help documentation and anything at that point that needs to be done can be opened as a new issue.
