### ISSUE TITLE
Significant digits too many in SE and CP estimates

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#331]
g-hat summary has 3 sig digits. That seems fine for all tables.
Not sure about M-hat as I can't get estimates yet (at least not with this data set).

**Comment by DAPPERstats** [comment]
switched the round to 3 digits for SE and CP in v 0.0.10.1 #342

**Comment by mhuso** [comment]
Using 10.7 SE estimates still have too many sig digits.
![image](https://user-images.githubusercontent.com/30159619/41439845-2f45e90c-6fe1-11e8-9ec0-fd9686f2ec82.png)

**Comment by DAPPERstats** [comment]
i think there was an issue with @ddalthorp merging some old code back into the master.
this was fixed with 0.0.10.1 and appears to be fixed again with 0.0.10.8
