### ISSUE TITLE
reporting of mean temporal split unclear

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#334]
The "mean" column in this summary using the Mock Data set is apparently used for plotting. It is not clear to the user what it represents. Can we drop it?
![image](https://user-images.githubusercontent.com/30159619/41207129-fb1e64b6-6cc4-11e8-9078-0413c5e0b1de.png)

**Comment by DAPPERstats** [comment]
removed in v 0.0.9.19 #336
