### ISSUE TITLE
Run status of datasets

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#350]
Here's a list of where we're at on ability to run a basic analysis for each dataset.  

- [x] **Wind RP**
  SE: OK - Some models fail
 CP: OK
 ME: OK *
 DP: OK

*SE Models involving season for class large will produce a non-crash error in mortality estimation.  

- [x] **Wind RP Bat**
  SE: OK
 CP: OK
 ME: OK 
 DP: OK

- [x] **Wind Cleared**
 SE: OK
 CP: OK
 ME: OK
 DP: OK

- [x] **Solar PV**
 SE: OK
 CP: OK
 ME: OK
 DP: OK

- [x] **Solar Trough**
 SE: OK
 CP: OK
 ME: OK
 DP: OK

- [x] **Solar Power Tower**
 SE: OK
 CP: OK
 ME: OK
 DP: OK

**Comment by DAPPERstats** [comment]
what inputs are you using for a basic model? (especially obviously for the ones that aren't succeeding yet)

**Comment by mintzj** [comment]
I'll make a note of which model got used where errors occurred.  I tried to keep it as similar and basic as possible in all cases, using season as a covariate when it was an option.

**Comment by DAPPERstats** [comment]
the wind RP Bat failed SE model is the same as the wind RP failed SE model (the fit for season on k fails)

**Comment by DAPPERstats** [comment]
the issue with the solar trough is the following:
- in the medium size class
- in the winter cell
- the distribution for `pdb` returned from `rcp` has a range that extends below 0
- within `calcg`, `pdb` gets converted to `pdb0` as part of a means to speed things up  
```
pdb0 <- exp(mean(log(pdb)))
```
 which returns `NaN` because a log of a negative

-if the code block to speed things up is skipped over (the code is treated as if there were < 10 searches even though there are more), the estimation works just fine. so whatever `ppersist` does to manage the negative values is good, but it hasn't been perpetuated to `calcg`.

@ddalthorp I think this is in your wheelhouse (it looks like it's associated with the updated `calcg` code, but correct me if I'm wrong). can you address this or let us know what needs to be done? thanks!

**Comment by DAPPERstats** [comment]
the solar power tower issue is because the sizeclass names in `data_DWP` don't match them in `data_CO` /the rest of the data set

if you change the column name in `data_DWP` from "small" to "sml" it works fine

**Comment by DAPPERstats** [comment]
what data set?

**Comment by mintzj** [comment]
The Wind RP dataset and the Wind RP Bat both gave me the "'by' argument is much too small" error.  I can post the issue since I was almost done writing it up but I didn't want to add a new one if we already have an issue for this.

**Comment by DAPPERstats** [comment]
sorry i meant "what data set" in response to "Is the issue (ME for large)..."

**Comment by DAPPERstats** [comment]
and no, the "by" issue is not covered elsewhere, as far as i know,

**Comment by mintzj** [comment]
I thought I got the same error for both Wind RP and Wind RP Bat, but I tried again to reproduce this issue for RP Bat, but I wasn't able to, so I will assume it is working now (I did upgrade to 0.0.11.3 from 0.0.11.2, which may have helped).

**Comment by mintzj** [comment]
Everything has run through error free on my end, with the exception of the "by" issue we discussed earlier. 
 I posted an issue for it (#388), but I"m not concerned about this for now.

**Comment by ddalthorp** [comment]
the `pdb0` issue needs to be addressed. I'll take a look presently.

**Comment by ddalthorp** [comment]
@dapperstats were you using lognormal persistence? The others should never have negative pdb's.

**Comment by ddalthorp** [comment]
Try replacing `pdb0 <- exp(mean(log(pdb)))` in `calcg` with:
```
    if (dist %in% c("lognormal", "Lognormal")){
      pdb0 <- mean(pdb)
    } else {
      pdb0 <- exp(mean(log(pdb)))
    }
```

**Comment by DAPPERstats** [comment]
@ddalthorp yeah, it was a lognormal for that size class
i've put this patch in w v 0.0.11.7 #393 and the code appears to work fine with no warning message thrown.

with that, the standard analyses on all of the data sets works fully through, so i'm going to close this issue. any remaining bugs, etc. can be brought up in specific issues.
