### ISSUE TITLE
error-checking SE

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#357]
- [ ] handling SE models that fit but without variance estimates (disallow in g estimates...many downstream effects). SE models that fit without variance estimates cannot be used in estimation of g. On the GUI side, such models will not be presented among the choices. However, such models might still be of interest to an R-savvy user from the command line and will be accessible there.
- [ ] handling SE models with only one search occasion (fit the model for p, but require user to commit to a choice of fixed K when estimating g or M).

**Comment by ddalthorp** [comment]
working on:
(1) traffic-directing and error-checking for special cases in pkm suite of functions,
(2) working on downstream consequences in, e.g., estM, estg, estgGeneric, plot, etc.

**Comment by DAPPERstats** [comment]
@ddalthorp is everything good for v1 (and if so can you close this issue?)? if not, what's still left?
