### ISSUE TITLE
show name of input data file somewhere on "Selected Data" screen in SE and CP analysis

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#359]

**Comment by DAPPERstats** [comment]
just right up at the top?

**Comment by mhuso** [comment]
Yeah... maybe just after the Show [10] entries

**Comment by DAPPERstats** [comment]
the "Show entries" is actually part of the HTML element
a good comparison is the "estimates" table. the options (vertically speaking) are either [1] where "size class" is or [2] where "download" is

**Comment by juniperlsimonis** [comment]
done w v 0.2.9 #545
