### ISSUE TITLE
diagnostic plots for pk models

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#361]
Right now we compare boxplots of p_hat and k_hat for each cell for a selected model with the boxplots for the "full model". That's a nice comparison, in theory. However, it is not uncommon for the "full model" to not be fittable for one reason or another. For example, if you are interested in Visibility and Season as covariates, then the full model would be p ~ Visibility * Season; k ~ Visibility * Season. That model will often be unfittable. 

What do we take as the baseline to compare the selected model to? There's not a clear choice. 

Is there an alternative?

One possibility would be to use pkm to fit each cell in succession. There will be failed fits for some of the cells, especially on the k side. We could show standard boxes for whichever p's and k's "work" and boxes extending from 0 to 1 (or some other indicator) for cases that don't work. 

A more robust and probably simpler approach would be to use EoA's cellwise Bayesian fits of pk, but there'd still be plenty of "if (this bad data) then (do this alternative)" and it would take me several days to pull all the pieces together and test.

A kluge for beta version might be to come up with a good ordering for relative fullness of the models, and show results for the fullest fittable model...a little hokey, but doable ("interpretable" is another question). This would be easy to code (in fact, it's already coded, but the ordering may not be the best).

Other ideas for simple diagnostics?

**Comment by mintzj** [comment]
Rather than our estimates extending from 0 to 1 in cases where our larger model fails to fit, could we drop down to a more general (smaller) model?  It seems like one wouldn't use 0 to 1 as the default given that they had no observations in a cell - it would be more informative to use a simpler model to fill in those missing cells.  I am not sure how practical it would be to implement this, you might need to carry around two models, your desired model and your fallback.

**Comment by ddalthorp** [comment]
Right on target, Jeff.

I guess the purposes of this diagnostic plot are manifold:
(1) show whether the selected model parses the data so that p2 > p1 for some cells (reflected in k boxes that extend from zero to one);
(2) show whether the selected model deviates far from the most tightly fitting model (not necessarily the "best" because of possible overfitting);
(3) show how a good small model gives tighter estimates than the most tightly fitting model but doesn't stray.
(4) show p and k estimates by cell
(5) show how the model performs in specific cells

(2) seems to give an immediate answer. Which non-failed model gives the tighest fit? The one with the greatest (unpenalized) likelihood. Define what we now call ("full model") as that model with the greatest `loglik` (as it's called in `survival`). That will be the full model in cases where that is fittable. In other cases, it is easy to identify which it is. 

[In version 0.0.10.7, `loglik` is not an element of pkm objects. In version 0.0.10.8 (to be released very soon), it will be.]

Thanks!

**Comment by ddalthorp** [comment]
`loglik` doesn't seem to work quite right.

**Comment by mhuso** [comment]
Maybe we shouldn't be fitting k for pj>pi, for j=i+1, Maybe we should be asking what is the likelihood of pj IF k==0.67 (default that I'm not wedded to, but is reasonable) and Nj=nj and Xj=xj. If we have p0>p1, then we have an initial k estimate and we can compare to estimated k for second search rather than a default. It seems like we're getting into trouble most often when we have little data to work with on second, third or subsequent searches.

**Comment by ddalthorp** [comment]
p2 > p1 is definitely an issue, but not a "failed fits" issue. The model is fittable when p2 > p1. The "failed fits" are more serious from a modeling effort, like empty cells or all carcasses found on first search or no carcasses available on second search (a different problem). If models fail, user will need to choose simpler formulas. If the data are incorrigible (e.g., they have only conducted one search), then they can choose a fixed k. 

If the p2 > p1 issue pops up (p[i+1] > p[i] for i > 1 doesn't seem to be a problem because that first search is so important), then the diagnostic plots and AICc help identify it and they choose a different model. If they don't, it's not ideal, but it's not the end of the world: (1) a somewhat too-small k is counterbalanced by a somewhat too large p, and (2) the uncertainty introduced by the uncertain k bumps the variance of the estimator up so it doesn't end up being too bad. They can usually do better by picking a different model form, but in the grand scheme of things I think it usually turns out to be more of a cosmetic issue than a substantive one (sort of like some lower quantiles of Mhat being less than X).

**Comment by DAPPERstats** [comment]
is the concern here assuaged with the shift from "full" to "reference" models and the use of the loglikelihood ranking? if not, is there anything left here to do for version 1 or are we good to go for now?
