### ISSUE TITLE
Table downloads not really tables

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#365]
Downloading the "Estimates" table results in a table of only 2 columns. Can we download
covariate     p     LCL    UCL    k   LCL   UCL  

as a table with 7 columns?

**Comment by mhuso** [comment]
On the other hand... downloading the M-hat table worked fine. Maybe just need to update the parameter tables for SE and CP

**Comment by DAPPERstats** [comment]
addressed as of v 0.0.11.1, the downloaded tables are now broken out into user-friendly columns
