### ISSUE TITLE
Mortality estimates by splits

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#366]
Table headings ignore user-selected alpha level
![image](https://user-images.githubusercontent.com/30159619/41492363-8b8e0fbe-70b3-11e8-9adc-972c3a88abc3.png)
Seems to always give 90% CLs even if I ask for 95% or 99% in General Input.

**Comment by DAPPERstats** [comment]
addressed in the major update v 0.0.11.1 and also in 0.0.11.3
