### ISSUE TITLE
zip-based install issues

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#368]
@ddalthorp what version of R are you using to make the builds you're adding? 

in trying to install from your zipped build, I get the following error

```
> GenEst::runGenEst()
Error: package ‘GenEst’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

i went back to an earlier version  (0.0.9.4)  of the zip you uploaded and run into the same error.

in googling a bit, it looks like R version 3.5.0 changed some of the internals and some packages might need to be force-rebuilt (even if the user already has an older version).

i can track this down/take care of it, but i was wondering if you could share here your session info for when you made the most recent zip build

**Comment by ddalthorp** [comment]
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

**Comment by ddalthorp** [comment]
3.5 sometimes not compatible with 3.4?

**Comment by DAPPERstats** [comment]
hmmm, i'm still getting the same error with the new build you put into the auxiliary folder.

**Comment by DAPPERstats** [comment]
ok, yeah, just figured that out:
![image](https://user-images.githubusercontent.com/23511502/41502570-d0b70820-7171-11e8-8048-bc000d78d059.png)

**Comment by ddalthorp** [comment]
This is going to be harder than I was hoping.

**Comment by ddalthorp** [comment]
I put the tar.gz up but am having trouble navigating the compiling with the new R installed on my user docs part of my hard drive instead of the program files part.

**Comment by ddalthorp** [comment]
I compiled it at win-builder with no trouble and uploaded it to auxiliary.

**Comment by DAPPERstats** [comment]
success!

ok, so we should be good here as long as any binary builds are done using R 3.5.0 (or later when that time comes).

these builds should work on earlier versions of R (back to a point, maybe 3.2?, whenever the last change like this happened), so anyone who's building (just you and me? maybe also @jeff) should just upgrade all machines now
