### ISSUE TITLE
arg = "YES" or "NO"

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#37]
in function calls, change all arg = "YES" (or "NO") to arg = TRUE (or FALSE); use some variation on:
if (arg) { 
   ans <- do_A()
} else {
   ans <- do_B()
}
instead of:
ans <- switch(arg, 
   YES = do_A(),
   NO = do_B()
)

Rationale is two-fold: (1) arg = T or F is extremely common (standard) in R functions, and users understand and expect that format, (2) logicals can be used as numeric if desired (by, say, some power user working from the command line).

**Comment by DAPPERstats** [comment]
this applies to fix_k only, right? or am i missing another spot?

**Comment by DAPPERstats** [comment]
done for fix k with v0.0.1.6
if there's another spot, reopen and let me know where. thanks!

**Comment by ddalthorp** [comment]
Excellent! I don't see another spot with that.
