### ISSUE TITLE
splits names in GUI

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#377]
"Search" and "Carcass" make some sense b/c that's where the columns are found, but they are cryptic. 

"Temporal" is not perfect a time-associated covariate  could be entered in the CO file, but it is 95% clearer than "search". 

"Carcass" is not the greatest either. Any ideas?

**Comment by DAPPERstats** [comment]
updated to "Schedule Variable" and "Observation Variable" in v 0.0.11.3 #383
