### ISSUE TITLE
fit CP model -- gray screen of death

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#378]
With the wind_cleared data:

![image](https://user-images.githubusercontent.com/30092223/41918203-b8e5912a-7910-11e8-9781-e3dd2cc3ebc5.png)

Runs and runs until it sounds like it is done. And then gray.

On the command-line side:
cpmSetSize with the same data runs fine.
cpmSetAICcTab runs fine on all sizes (as returned from cpmSetSize)
plot.cpmSet runs fine on all sizes (hundreds of graphs)

**Comment by DAPPERstats** [comment]
associated with the updates to the command line code
addressed with the updated front end in v 0.0.11.1 #381
