### ISSUE TITLE
Attempt to select less than one element

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#380]
Currently (0.0.10.11), this comes up for each of the datasets I've tried.  This occurs whether I select Size Class or not, and whether I select Predictor Variables or not.   I tried selecting less distributions to fit (for example, just exponential) but it didn't help.

1. Data Input:  Carcass Persistence Data File = CP_mock.csv
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Carcass Persistence: Last Time Present = LastPresentDecimalDays, 
                                                       First Time Absent = FirstAbsentDecimalDays,
                                                       Predictor Variables = Season, Distributions = (All)
4. Run Carcass Persistence Model

In the console:
```
Warning: Error in [[: attempt to select less than one element in get1index
  [No stack trace available]
```

**Comment by DAPPERstats** [comment]
associated with the updates to the command line code
addressed with the updated front end in v 0.0.11.1 #381
