### ISSUE TITLE
Warning full of Data

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#384]
When both season and visibility are used as predictors, a long warning message is produced which appears to contain raw data.  

1. Data Input:  Search Efficiency Data File = SE_cleared.csv
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = S1, S2, S3, S4, S5
                                                       Predictor Variables = Season, Visibility, 
                                                       Fix k = No
4. Run Searcher Efficiency Model

![image](https://user-images.githubusercontent.com/11892333/42066444-5e46197e-7af5-11e8-9dcf-9f5be9eebe6c.png)

**Comment by DAPPERstats** [comment]
ah, good catch, there was a new situation introduced with the partial fails (when k doesn't fit but the model is returned). 
it's patched now in v 0.0.11.4 #385
