### ISSUE TITLE
"vis * season" vs. "vis crossed with season"

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#39]
These labels appear in long lists. The former format is much easier to read/scan.

**Comment by DAPPERstats** [comment]
@mhuso specifically requested changing away from "*" and similar notation to something more familiar to people. I'm fine with it being whatever, just let me know if this is agreed on, or if y'all want something different than "*".

**Comment by ddalthorp** [comment]
I believe @mhuso was referring only to the ~ 1. In any case, A * B and A + B are much easier to read and scan than "A crossed with B" and "A and B". Also, the * and + notation are more precise ("hmmm...does 'A and B' mean 'A intersect B' or 'A*B' or 'A:B' or 'A+B'?") and probably more familiar to people as well.

**Comment by mhuso** [comment]
I agree. The issue was primarily in distinguishing R syntax ~1 that means estimated intercept only, from our context where we really want k = 1, sometimes, and estimated intercept other times. 
But the rest of the syntax, A * B and A + B is fairly common and can be clearly defined in the user guide so as to not be confusing to the user. It's also more compact so the window doesn't grow too large.

**Comment by DAPPERstats** [comment]
roger that, i'll switch those back.

**Comment by mhuso** [comment]
Thanks... 
still not quite sure how to best distinguish 1 from Intercept - maybe just that? And explain in User Guide?

**Comment by DAPPERstats** [comment]
I replaced all of the "~1" with "Intercept Only" a  little while back...is there an issue with that? Or is there a spot where we still need to get rid of the "~1"?

**Comment by mhuso** [comment]
Not, that sounds good to me. I haven't had much chance to get into the latest version. I will today.

**Comment by ddalthorp** [comment]
I know "Intercept only" was suggested quite awhile ago, but to me it sounds pretty cryptic. Something more along the lines of "constant"?

**Comment by DAPPERstats** [comment]
I'm fine with whatever in place there, just let me know (cc @mhuso )

**Comment by DAPPERstats** [comment]
updated w v 0.0.2.6
