### ISSUE TITLE
Can't estimate mortality with certain models

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#399]
I found a couple of CP models that the mortality calculation would not run for.  I am not sure if this is intentional or not. 

1. Data Input:  (All the Wind Cleared files)
2. Analyses > General Inputs: Number of Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analyses > Searcher Efficiency: Observations = S1, S2, S3, S4, S5
                                                       Predictor Variables = Season, Visibility, Fix k = No
4. Run Searcher Efficiency Model
bat: p ~ Visibility; k ~ 1
lrg: p ~ Visibility; k ~ 1
med: p ~ Visibility; k ~ 1
sml: p ~ Visibility; k ~ 1

5. Analyses > Carcass Persistence: Last Time Present = Left, 
                                                       First Time Absent = Right,
                                                       Predictor Variables = Season, Visibility, Distributions = (All)
6. Run Carcass Persistence Model
bat: weibull; l ~ Visibility; s ~ 1
lrg: lognormal; l ~ 1; s ~ Visibility
med: weibull; l ~ Visibility; s ~ Season * Visibility
sml: weibull; l ~ 1; s ~ 1

7. Analyses > Mortality Estimation: Fraction of Facility Surveyed = 1,
                                                        Date Found = DateFound,
8. Analyses > Mortality Estimation:  Estimate

When I try to estimate mortality, I get a UI error stating that we can't estimate mortality.
```
Mortality not able to be estimated
```
If I switch the weibull medium model to a simpler model such as weibull; l ~ 1; s ~ 1 it can estimate mortality.  Oddly however it can also estimate mortality using the more complex model
med weibull; l ~ Season + Visibility; s ~ Season * Visibility (delta AICc: 2.966)

Some working Med CP models:
weibull; l ~ Visibility; s ~ Season + Visibility (delta AICc: 0.77) 
weibull; l ~ Season + Visibility; s ~ Season + Visibility (delta AICc: 3.249)
lognormal; l ~ Season * Visibility; s ~ Season * Visibility (delta AICc: 14.273)
lognormal; l ~ Season; s ~ Season * Visibility (delta AICc: 19.973)

Non-working Med CP models:
weibull; l ~ 1; s ~ Season * Visibility (delta AICc: 5.902)
weibull; l ~ Visibility; s ~ Season * Visibility (delta AICc: 0)
weibull; l ~ Season * Visibility; s ~ Season * Visibility (delta AICc: 6.022)
weibull; l ~ Season; s ~ Season * Visibility (delta AICc: 10.364)

Any thoughts on what may be going on here?

**Comment by ddalthorp** [comment]
Thanks, Jeff. 

Are you working with the little patch I put up this morning or the older version?

**Comment by mintzj** [comment]
The version I tested with was 0.0.11.8.

**Comment by ddalthorp** [comment]
Can you try with 0.0.11.11 with changes from this morning?

Windows binary build is in auxiliary code folder.

**Comment by ddalthorp** [comment]
I tried it with the CP patch I put up earlier (and then built as 0.0.11.11) to repair some problems in the multi-scale CP modeling. It seems to work fine.

**Comment by mintzj** [comment]
The problem appears to be resolved.  After switching to 0.0.11.11 I was able to estimate mortality for each of the CP models which did not run in 0.0.11.8.
