### ISSUE TITLE
CP and SE tables

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#406]
Please add a column to each table: Number of carcasses initially in trial for each covariate combo.

**Comment by DAPPERstats** [comment]
is this something that needs to be done before the beta release? if so, please mark the milestone as "version 1". if not, please mark it as "version 2". (otherwise, i'm not clear what needs to be done right now) thanks!

**Comment by mhuso** [comment]
Not pre-beta, but for version 1, i.e., post beta. I think of version 2 as having big changes, like a DWP module...

**Comment by ddalthorp** [comment]
included in the latest updates (pending)
