### ISSUE TITLE
theta, beta, pk

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#41]
There was some confusion and inconsistency about notation in the original design meetings we had and the early versions of the coding that were sent to Juniper last summer. The theta was inspired by common notation for fitting MLEs. In some parts of the code, theta refers to the parameters on a logit scale; other parts on a linear scale. We should dump the "theta" and use "beta" for logit scaled parameters (following convention for linear models) and "p" and "k" when we transform back to linear scale cellwise.

Also, the earlier names of betaphat and betakhat should more appropriately be called betahat_p and betahat_k.

**Comment by DAPPERstats** [comment]
taken care of associated with updated naming conventions generally
edits are on my branch clean-up-se-model-functions  and will be merged into the master soon
