### ISSUE TITLE
truncate lower bound of splits to observed number of carcasses

### ISSUE THREAD

**Issue by juniperlsimonis** [ddalthorp/GenEst#412]
truncate the output (summary and plot) of a given split to being equal to or larger than the number of observed carcasses

**Comment by ddalthorp** [comment]
We have been looking at simulating from a truncated cbinom, and it looks promising. This will probably be the solution. At this point, I'm slightly unsure of all the details of the bias correction, but we will almost certainly be able to work it out for v1.0.0.
