### ISSUE TITLE
DESCRIPTION

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#42]
I had trouble editing the DESCRIPTION file because the line breaks were not interpretable by Notepad. I don't know how the v0.0.1.2 DESCRIPTION file was generated, but let's use the standard line breaks that Notepad can read.

**Comment by DAPPERstats** [comment]
I can open the version I have (from 2017-11-28 9:57 AM PST) fine in notepad. ANd I see you updated the doc for 0.0.1.3, but if I go back to the history to 0.0.1.2's DESCRIPTION file, it looks fine in the code editor on github. not sure what's going on here.

**Comment by ddalthorp** [comment]
I can open the 0.0.1.2 in Notepad, but all the fields are on one line with no apparent breaks. However, there are some apparently Github-esque line breaks that seem to be not properly rendered in Notepad.
