### ISSUE TITLE
a "save" button on model selection tab

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#420]
It would be helpful to have some indication that the selected models have truly been selected.

**Comment by juniperlsimonis** [comment]
they've been selected once they've been selected. adding a button leads to a false requirement to click things that aren't required.

**Comment by ddalthorp** [comment]
Agreed. This is a really modern thing, changing values in forms but not requiring confirmation via an explicit button click. I think the extra note in the mortality estimation tab directing user to confirm model selection coupled with a note in the User Guide will solve this.

**Comment by ddalthorp** [comment]
but they do need to click on "Model Selection"...

**Comment by juniperlsimonis** [comment]
this should be clarified by the edits in v 0.2.7 #543
