### ISSUE TITLE
option to download or display data for GUI figs

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#424]
...would allow users to draw their own graphs.

**Comment by juniperlsimonis** [comment]
oof, that's a mighty big ask with ugly consequences, given the complexity of the data sets involved and the limitations to downloading data (many of the figures have multiple data streams associated with them, which will require multiple csvs for a given figure). is this something that a GUI user is really going to want? if they want to make their own figures, it will be much simpler if they just go to the command line.

**Comment by ddalthorp** [comment]
This was an issue raised by one of the reviewers. I think you are right...users who want custom graphics should be using the command line. I'll add something to that effect in the User Guide.
