### ISSUE TITLE
general inputs, CI

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#428]
"We welcome the flexibility to choose a user-defined confidence level, however, this confidence level doesn’t seem to apply to the actual fatality estimation."

**Comment by ddalthorp** [comment]
I'm not sure what they are getting at with this comment, but their later comments (Tidhar) make it seem like they would like to adjust the CI for mortality estimation at the point of estimation (in mortality estimation tab).

**Comment by ddalthorp** [comment]
One reviewer (from France) called me this morning and strongly objected to 95% CI as default because it tends to be so wide that it gives great fodder for those who would argue that monitoring is pointless because the answer is so uncertain and vague and to get better precision would be very expensive --> disincentive to adopting the software. Also, 95% is markedly different from the confidence levels that are being adopted by regulators.

**Comment by juniperlsimonis** [comment]
i think this comment is like the others associated with the CL not making it through the maze of mortality plotting functions, which is fixed now.
