### ISSUE TITLE
show Inf or NA for Inf and NA data

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#43]
In display of CP data, show "Inf" or "NA" for right-censored CP values (instead of <blank>)
In display of SE data, show "NA" for NA cells in observation columns (instead of <blank>)

**Comment by DAPPERstats** [comment]
this doesn't appear to be something that can be changed easily.
i have SCOURED the documentation on data table presentations in shiny and haven't found something that allows an "as-is" presentation of NAs. it's quite frustrating. I'm sure there's a workaround or hack that exists, but for the time being, I think we can consider this for v2 of the app

**Comment by ddalthorp** [comment]
fixed...pending push

**Comment by ddalthorp** [comment]
somewhere on the interwebs...

The solution is simple, but it is not one that anyone in their right mind would be able to figure out:

```
options(htmlwidgets.TOJSON_ARGS = list(na = 'string')) #at the top of server.R

# and then ,,,server = FALSE for renderDataTable calls


```

**Comment by juniperlsimonis** [comment]
yeah, I figured it would be something pretty base-level (if you're writing out to the json script, that's usually pretty foundational)...and that call makes me thing someone else probably had a feature request (it's a buried argument). 

thanks for following up on this!

**Comment by ddalthorp** [comment]
yep. That's what it sounds like.
