### ISSUE TITLE
Cell = All...confusing

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#434]
"In the estimates tables, we suggest renaming the ‘Cell’ field to indicate that it reflects the different covariate combinations in the model. As it stands, if no covariates are used, it is unclear what this column represents, and that it contains the word ‘All’ under these circumstances it could be confused with representing, for example, all size classes."

**Comment by ddalthorp** [comment]
I find this confusing as well.

**Comment by juniperlsimonis** [comment]
this was addressed in v 0.2.7 #543
