### ISSUE TITLE
user guide and exponential distribution 

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#439]
"The user guide explains that the scale parameter in the exponential distribution will always be 1 by definition. Could this be reflected by the scale model field being removed under the Table and figure selection heading if an exponential distribution n is selected?"

Address this issue in the user guide explanation rather than the dropdowns.

**Comment by mhuso** [comment]
This is more elegant, but might cause minor problems if later someone is trying to put table together from other models.

**Comment by ddalthorp** [comment]
Scale for exponential in tables now reads NULL and User Guide has been updated too.
