### ISSUE TITLE
version and date

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#44]
Dates and version numbers are not consistent between disclaimer and "About" page. A good solution is to read the package date and version from the DESCRIPTION file whenever you want to reference them: 

packageDescription("GenEst", field = "Version")
packageDescription("GenEst", field = "Date")

**Comment by DAPPERstats** [comment]
great idea. do you have the time to create your own branch, update the code, and then create a pull request? if so, can you assign this to yourself?
if you notice stuff like that, it's easier/more efficient if you can just edit it.

**Comment by DAPPERstats** [comment]
nm, i got it.

**Comment by DAPPERstats** [comment]
completed with v 0.0.1.4
