### ISSUE TITLE
search schedule and g (GUI)

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#440]
" In the dataset used to trial the software, individual searches were sometimes conducted over multiple days due to the large area being searched. We initially entered these data as they were but got the error message ‘Search Schedule can't be averaged using date searched column’. This presumably means that the software doesn’t like there being slightly different search schedules for different units, which is perfectly reasonable but not clear from the user guide."

**Comment by ddalthorp** [comment]
Different search schedules for different units should not be a problem. There was an error in calculating mean in a recent version of the software, but I believe that has been corrected.

**Comment by juniperlsimonis** [comment]
yeah this shouldn't be an issue now.
