### ISSUE TITLE
Excel date formats

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#444]
"The date format in our .csv files kept reverting back to the wrong format every time we modified them. We guess the fix for this would be changing the default formats in Excel but this was irritating and should perhaps be noted in the user guide." [Tidhar]

It's not clear to me what the issue is. Possibly a difference between European and US writing of dates?

**Comment by uroshm** [comment]
You are correct, there is a CSV baseline format that is being used. Here is some advice from ZenDesk for resolving the issue:

Open your file in Microsoft Excel
Right-click the column containing dates
Select "Format cells"
Click "Date" under Number >> Category
Ensure the Location (Language) is set to be United Kingdom (English)
Select formatting that shows the date in the dd/mm/yyyy format

If you want to change the format, you can go into Excel settings or create a macro which executes every time the program loads.

Finally, here is another resource on the matter:
https://excelribbon.tips.net/T011575_Setting_a_Default_Date_Format.html
