### ISSUE TITLE
GUI figs on small monitor

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#447]
"I’m using a smaller computer (13” laptop) and I select “Size Class Column” in the Analyses tab.  I can’t see below the first option so go to the right to find a slider (which only shows up when the options are available to choose and takes a few seconds to show up).  Mouse clicking on either the slider or the arrow down or up causes the option box to close instantly.  I tried more times and now occasionally when I mouse over to where the slider would be it doesn’t show up and then the option list flashing position marker freezes." [Craig]

**Comment by juniperlsimonis** [comment]
can you get some screen shots from this person? on my small (12 in) laptop, even with the resolution turned way down to 800 x 600 and the browser zoomed in to 300%, i can still manage to select a size from the drop down just fine.

**Comment by ddalthorp** [comment]
Awhile back, I recall a similar problem but thought it was resolved too.
