### ISSUE TITLE
Size columns

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#45]
We need a GUI option to not require a 'size' column in both the CP and SE modeling sections.

And how should we do the error-checking on the sizes? It seems like both SE and CP will need to have the same size levels and the carcass observations file cannot have size outside of the SE and CP sizes.

**Comment by DAPPERstats** [comment]
there is no requirement for the size class to be filled in for either model
that's correct. the requirement is that size class categories are the same across combined analyses. it'll need to be managed at the g function and the mhat function spots.

**Comment by ddalthorp** [comment]
I see that now...but when I was working through an analysis, I get the (wrong) impression that a choice of size class is required. Can we have some indication that that is an optional variable?

**Comment by DAPPERstats** [comment]
so, just an "(optional)" on the gui?
the same is true for the predictors. do you want it for both?

**Comment by DAPPERstats** [comment]
i'm fine with them being together or separated, just let me know what you want (cc @mhuso )

**Comment by DAPPERstats** [comment]
included "optional" onGUI in v 0.0.2.6
