### ISSUE TITLE
file types for download

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#450]
"When I ran mortality estimation for Example 2, I attempted to download and save the figure, but it does not allow changes to “Save as type” which is blank, and thus the file cannot be reopened by any programs on my computer. The same thing occurs for “Summary” where the User Guide states you can download in tabular format. I cannot save it as a specific file type. In fact, when I attempted to download any of the figures or tabular data, I could not reopen the files. At this time, I would be unable to incorporate the figures and output into a report due to this issue."

**Comment by juniperlsimonis** [comment]
this seems like a user error, and my guess is they're not using the download buttons. the download buttons save the tables as csvs and the figures as pngs 

if they're getting a dialog where "save as type" is a field, it means they're likely right clicking on the figure. in that situation, they actually could type in "filename.imagefileextension" (where imagefileextension could be jpg, png etc etc) and it would save. not that we want them to be going that route but just as an fyi.

**Comment by ddalthorp** [comment]
I'll put a note in the User Guide.
