### ISSUE TITLE
User Guide: SS vs. CO covariates

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#456]
If covariate column is included in both SS and CO, it is counted as a CO covariate in the estimation. This is a subtle distinction that is unlikely to make any noticeable difference except in extraordinary circumstances (abrupt change in seasonal parameters from one interval to the next and an unusually large number of carcasses found soon after the change).

**Comment by mhuso** [comment]
What are the consequences if two distinct variables selected for splits, one in SS, one in CO, share the same name?

**Comment by ddalthorp** [comment]
ouch. That should be disallowed.
