### ISSUE TITLE
automatically switch to populated model table tab when model done running

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#46]
After CP and SE models are run, automatically move to "Model Table" tab with an AIC table already filled out for one of the sizes. In many cases, analyses will need to be done for a single size only, and the superfluous clickage can be annoying.

**Comment by DAPPERstats** [comment]
code for the switching of tabs: https://shiny.rstudio.com/reference/shiny/latest/updateTabsetPanel.html

the auto-selection of sizes and auto generation of AIC table will need to be managed separately from the switching (from a coding perspective)

**Comment by DAPPERstats** [comment]
done w v 0.0.2.5 in https://github.com/ddalthorp/GenEst/pull/62
