### ISSUE TITLE
Example data should be available from within the GUI

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#462]
I'd like to see a drop-down menu that allows the user to automatically auto-populate all of the data for a mock scenario with one click, rather than having to upload CSVs.  

As a stop-gap workaround, a one-button download of a zip that includes the .csv files should be added for the shiny.io version of the app.

**Comment by ddalthorp** [comment]
I'm not sure this is a good idea for the published version. The tutorials and data structures are designed to bring the user through the steps of an analysis, which, among other things, includes uploading data.

**Comment by prabie** [comment]
Interesting point.  My thinking for the beta version was that having example data ready-to-go in the app might make the difference between a beta-tester trying things out and a beta tester putting it aside (and not getting back to it).

**Comment by ddalthorp** [comment]
agreed.

**Comment by juniperlsimonis** [comment]
done with v 0.1.10 #506
