### ISSUE TITLE
Alpha level didn't change mortality estimate CI

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#464]
I ran "Estimate" mortality. Then decided I wanted 90% not 95% CI. I changed general input to 90 then reran "Estimate." CI did not reflect change.
Also, above graph is very small and hard to read.

**Comment by ddalthorp** [comment]
Ah-ha! One of the reviewers alluded to this problem, but I didn't quite understand the comment.

**Comment by mhuso** [comment]
I think we addressed this a while ago, but somehow it was lost between versions.
The summary table also doesn't respond to the changed alpha.

**Comment by juniperlsimonis** [comment]
updated in 0.1.8.
