### ISSUE TITLE
Can't split on search date in example Cleared data

### ISSUE THREAD

**Issue by mhuso** [ddalthorp/GenEst#465]
![image](https://user-images.githubusercontent.com/30159619/44426706-3926bf80-a544-11e8-9651-726e065ae5d1.png)
Is this to be expected? That we can't estimate by search date for our example bat cleared data?

**Comment by ddalthorp** [comment]
No....there's a problem somewhere.

**Comment by ddalthorp** [comment]
fixed in 0.1.7
