### ISSUE TITLE
GUI: fix k in Mortality tab?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#477]
"When fixing k to a specific value, GenEst ask after the analyses whether we would like to fix k to a specific value. But we actually have done this. Seems to be a bug?"

**Comment by juniperlsimonis** [comment]
I cannot replicate this issue. I'm presuming from the quotes that it's a reviewer comment? Do you have anything more to go off of or are you able to replicate this issue? 

note that if you fix k but only have one observation, it will tell you that it has ignored the fixed k value for the model fit (you'll get a warning yellow box), and it will request an assumed k when you go to the mortality page, as it should. the value in the M assumed k box is updated to reflect the selected k on the SE page even though it wasn't used, though, so the user shouldn't have to change anything if that was the value they wanted to use still.

**Comment by ddalthorp** [comment]
Yes, the quoted issues are from reviewers. I ran into some troubles (bugs as opposed to labels and other cosmetics) with challenging data from reviewers but I believe I fixed everything I ran into...not sure if this was one of the fixed problems.
