### ISSUE TITLE
GenEst "home page"

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#479]
Clicking on the GenEst logo in the upper left corner of the GUI brings up the GitHub page. It is not clear how users could get back to their in-progress analyses from there. Clicking the browser's back arrow bring up a clean version of the GenEst app again with all work (inputs, models) lost.

**Comment by juniperlsimonis** [comment]
ok, so do you not want it to link to anything then? this was suggested a while back by someone (jeff, i think?), so i added the link. it's easy to remove the link if that's what you want.

**Comment by ddalthorp** [comment]
It does make sense to have it go to GitHub, but it kills the active data and analysis, which is Not Good. Let's remove it for now unless you can think of some other solution.

**Comment by juniperlsimonis** [comment]
removed as of 0.1.8
