### ISSUE TITLE
GUI: update files --> clear analysis windows

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#483]
When new data files are uploaded after a previous analysis, clear the previous results tabs to avoid a mismatch between data and results.

**Comment by juniperlsimonis** [comment]
how much of a change do you want for each data file? like, if i run through a full analysis and then realize i have the wrong CO file, do you want all of the previous results tabs to clear? What about for a wrong SE file?

i'm guessing there's a not-clean answer to this (what should be cleared will depend on which file is updated)... if that's the case, can you please write out explicitly what should be cleared when each file is updated? thanks!

**Comment by ddalthorp** [comment]
Uploading new file --> clear the corresonding "Analyses" tab and any downstream analysis tabs that rely on the updated data.

SE --> clear all data from Analyses > Searcher Efficiency, Mortality Estimation, Detection Probability
CP --> clear all data from Analyses > Carcass Persistence, Mortality Estimation, Detection Probability 
SS --> clear all data from Analyses > Mortality Estimation
DWP --> clear all data from Analyses > Mortality Estimation
CO -->  clear all data from Analyses > Mortality Estimation

**Comment by juniperlsimonis** [comment]
ok, this is all handled as of  v0.2.13 #556
