### ISSUE TITLE
GUI: "DWP column" drop-down in Mortality estimation tab

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#485]
Disallow invalid data columns, i.e., columns that contain numbers outside (0, 1] or letters.

**Comment by ddalthorp** [comment]
and have it be conditional...parse to see if it's necessary.

**Comment by juniperlsimonis** [comment]
it is already conditional... or it should be... if it's not, when is it appearing when you think it shouldn't be?

**Comment by juniperlsimonis** [comment]
this should be addressed with v0.2.11 #550 but let me know if not
