### ISSUE TITLE
GUI: mortality tab, "estimate" button

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#486]
A common user error is to go to the mortality analysis tab before selecting SE and/or CP models. Once there, user may see the instruction "Run estimate to view figure," which will make no sense because that button does not appear. Instead, if user has not selected SE or CP model yet, direct users back to the SE and CP tabs to select models.

**Comment by juniperlsimonis** [comment]
updated in 0.1.8
