### ISSUE TITLE
pkmSetAICcTab function call...

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#503]
...has three args (2x) `pkmSetAICcTab(rv$mods_SE[[rv$sizeclass_SE]], TRUE, TRUE)` in app_rv_update_functions.R but function definition has only two args `pkmSetAICcTab <- function(pkmset, quiet = FALSE){` in searcher_efficiency_functions.R

**Comment by juniperlsimonis** [comment]
it has 3 arguments now, so that it could be toggled between the app and command line versions

**Comment by ddalthorp** [comment]
Very interesting...I didn't see the three args in the function definition in searcher_efficiency_functions.R when I cloned the repo to my computer, but I see the args plain as day in the version that's posted at GitHub. This stuff drives me crazy.
