### ISSUE TITLE
default values in drop-downs

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#505]
if there is only one eligible column, that is the default. if there are several, no default.
 
disable ineligible columns from all drop-downs (obsCol may be a challenge).

**Comment by juniperlsimonis** [comment]
to facilitate that, it will help immensely to have an explanation of what constitutes eligibility for each input where this still needs to happen

**Comment by juniperlsimonis** [comment]
bumping the request here for additional info to facilitate addressing this

**Comment by ddalthorp** [comment]
Here's what I'm thinking...if anyone has contrary ideas, please chime in.

- [ ] predictors for SE and CP should not have NAs

- [ ] obsCol_SE columns should have at least one value of 0 or 1.

- [ ] ltp must be numeric && finite && non-negative

- [ ] fta must be numeric && non-negative

- [ ] DWP column must be numeric && in interval (0, 1]

I was also thinking that length(SE$sizeclassCol]) should be strictly greater than length(unique(SE$sizeclassCol)) [ditto for CP] to filter out continuous measures (e.g., 13.3 cm) and unique IDs, but this would be a bit intricate to manage.

**Comment by juniperlsimonis** [comment]
ok, these are all handled in v 0.2.11 #551 
the dropdowns are substantially reduced now and there's a lot better 
if there are further qualities that should be included, just let me know, but i'll close this for now
