### ISSUE TITLE
Removing vestigial files?

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#51]
Given that we've got the app code within the package now, there's now a bunch of vestigial code: the app folder, and the 5 R scripts that are in the top level all aren't being used now.

Are you all ok with me removing the old files and moving the LICENSE into the package folder, then removing the "GenEstPackage" folder in the hierarchy so that's the main repo now? (that is, rather than the main repo being what you see here https://github.com/ddalthorp/GenEst now it would be what you see here https://github.com/ddalthorp/GenEst/tree/master/GenEstPackage now, plus the LICENSE, and also a README.md)?

(@ddalthorp @mhuso )

**Comment by DAPPERstats** [comment]
i should also note that thanks to the wonders of versioning, we can recover any of these files later if the need should arise, so they'd be deleted from the visible present version, but would exist in the archived code.

**Comment by ddalthorp** [comment]
makes sense

**Comment by DAPPERstats** [comment]
done with update to v 0.0.2.1 
version upped to 0.0.2.x because of removal of previous code folder (the app folder), removal of old files, and the removal of a level in the folder hierarchy
