### ISSUE TITLE
Reset buttons needed

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#510]
The GUI needs reset buttons to clear previous work.  You can accomplish this by reloading the app but that feels extreme from a user perspective. You can also use the keyboard to erase many of input text fields but it's not intuitive because one populates those from drop down menus.  I suggest reset buttons for each of the following functions:

-Clear this analysis (CP SEEF etc)
-Clear this data file
-Clear this estimate

Maybe others, too.

**Comment by rwolpert** [comment]
Thanks!
-- 
----------------------------------------------------------------------
 Prof. Robert L. Wolpert : <rlw@duke.edu>  :     +1-919-684-3275
 Duke Univ. Dept. of Statistical Science   : 211c Old Chem, Box 90251
 & Nicholas School of the Environment ES&P :    stat.duke.edu/~rlw/

**Comment by ddalthorp** [comment]
This is a good idea. 

...and when, say, SE data are cleared, M and g estimates should be cleared as well to avoid mismatch between results and the data they are based on.

**Comment by juniperlsimonis** [comment]
every major button (data input, run SE and CP model, estimate M g, split M) now has a "clear" counterpart that clears out everything downstream

as of v0.2.14 #557
