### ISSUE TITLE
GUI reorganization

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#512]
Suggest a reorganization of the GUI.  The Help tab is stylistically unlike the other tabs, and probably ought to be the first tab to open, to orient people to the software.  Suggest the help tab be designed (like the other tabs) with sub-tabs, in the following order:

1.  Disclaimers (so that it will be the first thing people see; then we can drop the pop-up disclaimer). 
2.  Welcome tab, with a blurb about the 
  -purpose of the app, 
  -how to download example data, and 
  -where to find documentation (currently, the downloads tab, but for the CRAN version there will need to be a link to the User Guide b/c CRAN will object to including the pdf with the package)
3.  About tab, with the authorship & sponsorship information
4.  Downloads tab
5.  Leave feedback tab

**Comment by ddalthorp** [comment]
I resolved most of these issues, mostly by creating a new tab with subtabs = "getting started" (matching your description of "welcome" tab), "downloads", "help" (including links to the User Guide and technical manual along with information about version number, authors, sponsorship), "disclaimers" (with the WEST disclaimer and "provisional" USGS disclaimer). 

1. the "provisional" USGS disclaimer pop-up no longer appears at startup,
2. I didn't get a "feedback" tab built,

For the data set downloads, I just point to the inst/extdata folders, zip the user's desired data files together, and download via href with target = "_blank". I use a little R package called "zip" that creates nice little zip archives appropriate for the OS that the user is working on. Fully compatible across platforms and makes things really easy.

The code for the other pieces is a bit choppy and breaks up the slick `shiny` code flow and aesthetics that Juniper set up, but hopefully I didn't mess things up too bad. In one ugly chuck of code in particular (in server.R), I have several functions that are virtually identical, differing only in some fixed constants within the functions. These are linked to separate `downloadButton`s. A nice way to do it would be to use just one function and have the download buttons pass the appropriate parameters to the function, but I couldn't quite figure out how to get that accomplished.

**Comment by prabie** [comment]
Great improvements!  A couple thoughts:

1.  Let's not add a feedback tab because I don't want to solicit feedback within the app after it is released.  WEST has committed to maintain the package and host the app.  We're not providing product support.  

2.  The first paragraph of the WEST disclaimer doesn't need to go in the CRAN version.  It's only relevant to people using the app on the WEST-hosted Shiny.io service.  People using the app locally aren't transmitting data beyond their own machine.

3.  I like that the version number is easy to find but I don't think it's a very descriptive tab name.  I suggest "Help & downloads"  or just "Help" or "About."  

4.  The "Help" subtab is really _About_, not _Help_

5.  I think the app should open on the (renamed) v0.2.4 tab to remind new users that help and downloads are available.  

6.  I don't care if the app does not open on the disclaimers tab but I'm calling it out because I thought USGS might need the app to open on a disclaimer.

**Comment by ddalthorp** [comment]
1. OK!
2. OK!
3. I was originally thinking "Resources" for the tab name because it has links for "help", data "downloads", "disclaimers", and "about" info. 
4. We should have the version number visible at the top of every page. I'm not savvy enough in `shiny` to put it up there gracefully as text in an appropriate way. I could learn, but it would be great if someone else could take that on.
5. OK!
6. With provisional software, the disclaimer needs to be in-the-face. I don't know what the expectations are about approved software. I have a call with the powers-that-be this afternoon and will ask.

**Comment by ddalthorp** [comment]
Resolved in my next PR
