### ISSUE TITLE
commas and semicolons

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#527]
Check whether the user's .csv files use semicolons or commas as a separator and allow either (in much of Europe, Excel uses semicolons as a .csv field separator).

**Comment by ddalthorp** [comment]
I added a radio button to toggle between read.csv (comma separator for fields, period separator for decimal) and read.csv2 (semicolon separator for fields, comma separator for decimal)). (available in my next PR)

**Comment by juniperlsimonis** [comment]
something isn't working right with this... it's bombing when i try to load any files.
i'll work on this with the code i'm updating now, and will make it so the user doesn't need to manually select the option

what might also be a good idea is to have a european style version of example data?

**Comment by ddalthorp** [comment]
should be rv$data_CP <- rv$csvfun(... in place of rv$data_CP <- csvfun

Ditto for rv$data_SS <- csvfun(... and rv$data_DWP <- csvfun and rv$data_CO <- csvfun

A Euro version of the .csv's is a good idea. There'd need to be some traffic directing to load the right ones.

And auto-parsing the .csv's to eliminate the need for the radio button is great.

**Comment by juniperlsimonis** [comment]
addressed in #540
