### ISSUE TITLE
'deployment' folder?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#534]
This is a permanent feature or just there for the beta2 review process?

**Comment by juniperlsimonis** [comment]
are we planning to have a permanent web deployment on west's shiny server @prabie or anywhere else? if so, we should retain the folder. it's listed within the `.Rbuildignore` file, so it won't be built into the R package.

**Comment by prabie** [comment]
Yes, WEST is planning to continue to host GenEst after release.

**Comment by juniperlsimonis** [comment]
i thought so. then yes, this is a permanent feature.

**Comment by juniperlsimonis** [comment]
the deployment folder will get updated once everything else is all ready 
and no, those need to be in two separate places, one for each version of the app
