### ISSUE TITLE
remove modal disclaimer?

### ISSUE THREAD

**Issue by juniperlsimonis** [ddalthorp/GenEst#539]
with the inclusion of the disclaimers on the `help/resources` tab do we even need the modal disclaimer at all anymore? 

@ddalthorp it looks like you commented it out in this version, which is usually what i do when i'm working so i don't have to bother with it, so i wanted to double check... is the new location sufficient for the USGS disclaimer?

@prabie is the current location of the disclaimer for WEST within the `help/resources` tab sufficient?

**Comment by ddalthorp** [comment]
I think we probably won't need the model disclaimer. I sent an email to our code guy to ask him that. If I don't here from him by Monday afternoon, I'll call. Let's leave it commented out for now and (probably) remove it later.

**Comment by prabie** [comment]
I think WEST will be ok with the location of the disclaimer.  If not I can move it later.

**Comment by ddalthorp** [comment]
we don't need modal dialog disclaimer for USGS
