### ISSUE TITLE
show version number on top of page

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#546]

**Comment by juniperlsimonis** [comment]
it's on the window title

**Comment by juniperlsimonis** [comment]
![untitled](https://user-images.githubusercontent.com/23511502/45932844-a78de180-bf37-11e8-9b28-4c6d1c725a00.png)

**Comment by ddalthorp** [comment]
I don't see it. Can we put it somewhere that I'm likely to see it if someone sends a screenshot when asking for help with something? E.g.

![image](https://user-images.githubusercontent.com/30092223/45933180-8bd90a00-bf3c-11e8-8856-d528621d3b9b.png)

**Comment by juniperlsimonis** [comment]
that's a consequence of you having too many tabs open so the names are shortened, you should see it in the title if the titles aren't getting shortened, yeah? (what browser are you using?)
in any case, it's possible to add the version number in anywhere we need it

**Comment by ddalthorp** [comment]
Great! I couldn't figure out how to get text onto the navbar.
