### ISSUE TITLE
error pre-checking in SE and CP model building

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#55]
in drop-down menus, do not show improperly formatted columns as possibilities for variable selection (?)

**Comment by DAPPERstats** [comment]
that's a really low priority

**Comment by DAPPERstats** [comment]
@ddalthorp i'm marking this as for version 2, if you're ok with that?
it's totally doable, but will be a modest amount of work
i think we'll need to write up what the format requirements are for each input first and then we can use that document to craft the code. that'll make it a lot easy to translate over.
but yeah, for now, i think this is low priority.
