### ISSUE TITLE
size class and AIC in SE and CP modeling

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#56]
Update the displayed AIC tables in SE and CP modeling tabs automatically upon choosing a different size class rather than requiring user to click the "Generate AIC table" button again. As it stands, there can be a mismatch between the chosen size class and the summary of models given in the table (i.e., after selecting "medium," results show "small" until "Generate..." is clicked). [Also, the extra required click is distracting.]

**Comment by DAPPERstats** [comment]
accomplished w v 0.0.2.7
