### ISSUE TITLE
CP exponential model giving output for 2 parameters

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#561]
I used the example mock data set and modeled persistence with season as the sole covariate.  Top model is exponential with l~constant, s~constant, and there are parameter estimates for both location and scale.

Screen shot attached

![image](https://user-images.githubusercontent.com/30160602/46089133-1bfc9680-c16b-11e8-8364-c8359f51e437.png)

**Comment by ddalthorp** [comment]
I see that the scale is exp(1) with no uncertainty. Should be NULL, I believe.

**Comment by ddalthorp** [comment]
Technically, it should be 1 instead of exp(1), but in the model, the scale parameter for the exponential is ignored, so it is just a display issue. I agree that NULL is clearer. 

I'm making the change in cpm: if ("exponential") cellMean_s <- 0 [rather than 1], so exp(cellMean_s) = 1 rather than e.
