### ISSUE TITLE
gray screen

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#564]
mock data
size = Size
SE models: fix x = 0.7 for S
run models and select constant, constant for each model
CP models: constant exponential for each
Mortality estimate --> gray screen 
```
Warning: Error in if: missing value where TRUE/FALSE needed
  74: msgModDone
  73: observeEventHandler [C:\Users\ddalthorp\Documents\R\win-library\3.5\GenEst\app/server.R#152]
   2: runApp
   1: runGenEst
```

**Comment by juniperlsimonis** [comment]
oh shoot, i was dealing with the edge cases and didn't pull out all of the crutches i left in elsewhere
that issue should be fixed with 0.2.16 #566
