### ISSUE TITLE
deployed version downloads empty zip files

### ISSUE THREAD

**Issue by juniperlsimonis** [ddalthorp/GenEst#574]

**Comment by juniperlsimonis** [comment]
@prabie raised this issue in email
it looks like i can get the download, but (just like the local version of the app) it's actually a nested set of folders that can sometimes be not apparent.
i'll take a look at the code and see if i can improve it, but the data should actually be there (i can get them when i deploy a version on my shiny apps server)

**Comment by juniperlsimonis** [comment]
this should be handled with v 0.2.19 Download zips #577
paul can you double check? thanks!

**Comment by prabie** [comment]
v 0.2.20 fixes both of the issues I raised yesterday.  Thank you!

**Comment by juniperlsimonis** [comment]
great!
