### ISSUE TITLE
search box on tables?

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#582]
This is puzzling. What's it for? Can we remove it?

E.g.:
![image](https://user-images.githubusercontent.com/30092223/46239024-89651e80-c347-11e8-9c1e-9732cb655133.png)

**Comment by juniperlsimonis** [comment]
you can use it to search the table. and 
that's part of the data table output structure
yes we can remove it if we want https://rstudio.github.io/DT/options.html

**Comment by ddalthorp** [comment]
What would we want to search for in a necessarily short table?

**Comment by juniperlsimonis** [comment]
IDK, it's in there by default, so i've left it in. if you have a long list of models it can definitely be helpful, same if you have a long list of data in a file.

**Comment by ddalthorp** [comment]
I wouldn't want to take it out if people would find it useful, but I'm just not seeing how it would be helpful with a long list of models (which is still a short table...).

**Comment by ddalthorp** [comment]
let's keep it.

**Comment by juniperlsimonis** [comment]
something that is surely doable, but low enough of a priority to wait until v 2 given the situation, is making it dynamic, such that only tables long enough to be cut off to another "page" (where you have to click through the table at the bottom) get a "search" field.

**Comment by ddalthorp** [comment]
I meant...let's keep it the way it is. 

99% of the time it will be ignored, but there is a (somewhat obscure) use for it.
