### ISSUE TITLE
data

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#585]
CRAN may balk at us trying to put 5 essentially identical copies of the data into the package.

I'm wondering if we can just use the .Rdata version and then create .csv's for download when the user clicks to download. This would work best with a toggle for format  somewhere (semicolon or comma). 

As stand-alones, the .csv's take up nearly 3 MB. By contrast, the .Rdata's take up about 70 kB total.

**Comment by ddalthorp** [comment]
Having just one copy rather than 5 makes it a heckuvalot easier and safer to make changes too!

**Comment by juniperlsimonis** [comment]
what do you mean 5 copies of the same data? there's just the `.Rdata` and the `.csvs` in `inst/extdata`, right? and I get the whole `inst/extdata` folder as 700-800 kB, not 3 MB?
![image](https://user-images.githubusercontent.com/23511502/46320518-a3933c80-c593-11e8-8b85-f5f113c3838b.png)

**Comment by ddalthorp** [comment]
OK. it looks like only three (please forgive my bad memory...I thought we had separate copies for "app" and "deployment" but that was just the User Guides (issue is resolved) and the icons (issue is just the way it is...no way around it):
1. .Rdata
2. .csv
3. csv2

**Comment by juniperlsimonis** [comment]
where are csv2?

**Comment by ddalthorp** [comment]
They aren't there, but they were on the agenda. 

But that requires maintaining three identical copies of the data and an extra 1.5 MB storage.

**Comment by ddalthorp** [comment]
I figured out a solution...keep just the .RData's and provide links to download in either .csv or .csv2 format. For the other downloads, mimic the format of the last upload.
