### ISSUE TITLE
clean up SE and CP figs

### ISSUE THREAD

**Issue by ddalthorp** [ddalthorp/GenEst#59]
interpretability and legibility need improvement

**Comment by DAPPERstats** [comment]
can you give me specific things to address or mockups of what you'd like to see?

**Comment by ddalthorp** [comment]
For SE figs,
1. currently there is nothing to distinguish full model results from selected model results (all are same color and same line pattern);
2. in the line graphs, add labels to the points to show how many carcasses were available and found on each search
3. eliminate the redundant x- and y-axes in the arrays of plots to reduce (or eliminate) the margins between graphs where possible...this puts more space within the figs proper, so that features within can be seen more clearly (like labels on the points). 
4. instead of putting the identifying labels in an ambiguous position as tiny font titles between figs ("Hmm...is that the label on the x-axis of the plot above or the title of the plot below?"), put the labels inside the plots as text() or mtext()).
5. give a description of what the covariate levels represent...right now they just show the level (e.g., "RP") but no indication of what the covariate is (e.g., "visibility"). This is consistent throughout all the figs, so one explanation for the whole page would be sufficient.

**Comment by ddalthorp** [comment]
For CP figs, I get an error and see no graphs at all (v0.0.2.2).

**Comment by DAPPERstats** [comment]
SE figures updated with v 0.0.3.1.
now also includes functionality to support `plot()` on pkm and pkmSet objects

CP figures were edited a while back and will be again with updated functionality. any specific issues can be brought up at that time
