### ISSUE TITLE
Possible to get NaN values for g with some data sets

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#591]
Confidential data set shared with Juniper and Dan.

**Comment by ddalthorp** [comment]
A few issues...
1) the dates were not formatted properly. The program required dates to be yyyy-mm-dd or mm/dd/yyyy, but the data set had yyyy/mm/dd. The new version (0.3.5) has greater flexibility on dates (including allowing yyyy/mm/dd).

2) Search dates are assumed to be in increasing order, but there was no check on that. I put in a check. The SS data had some errors in it.  In particular, the SS dates should probably have the following corrections
 ```
data_SS$Date[4]   <- "2016/04/17"
data_SS$Date[104] <- "2016/09/28"
data_SS$Date[242] <- "2017/05/05"
```

With the corrections to the data and the more flexible date parsing, I had no trouble running the data set.

**Comment by prabie** [comment]
Thanks, Dan.  Funny, I thought I'd sorted the SS table on date but I must
be mistaken.  I also am able to generate estimates.

* Paul Rabie,  Ph.D*
*Research Biometrician*
*ESA certified Ecologist*

Western EcoSystems Technology, Inc.
Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
307-755-9447
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.
