### ISSUE TITLE
Bad CO data throws error about invalid k value

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#592]
I uploaded data to the GUI that included a carcass observation at a unit that was not included in the CO file.  The error that GenEst threw was about an invalid k value.

**Comment by ddalthorp** [comment]
I can get that GUI error ("Invalid value for assumed k input(s)") when there is a problem in the dates, but I cannot find anywhere in the code (or on my computer at all!) that has the phrase "Invalid value" so I have no way of finding or fixing this issue.

**Comment by ddalthorp** [comment]
I did find the file (...was limiting the scope of my search too much the first time), and it was an easy fix.
