### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by prabie** [ddalthorp/GenEst#593]
Suggestion for a later date:  wrap the function calls associated with "run model" buttons in the GUI in try-catch statements with the catch function returning the error message to the user and an indication of which function errored out, or the purpose of the function that errored out.  Two advantages to this: 
 1. Avoid the grey screen of death.  2.  Give users the information that is available.  Much of the time it will be too cryptic to be useful but it may on occasion provide a clue.  People using the version hosted on the Shiny.io service do not have access to the command line

**Comment by ddalthorp** [comment]
v1.2.0 has more robust error-checking and more informative error messages in many places. 

This will be an ongoing issue for quite some time. Closing it as an issue for now. Reopen to note specific errors to catch.
