### ISSUE TITLE
matrixStats: Upcoming version requires using useNames = TRUE in two places

### ISSUE THREAD

**Issue by HenrikBengtsson** [ddalthorp/GenEst#657]
Hello. The **matrixStats** package will soon be updated to output row and column names consistently.  The current behavior is `useNames = NA` for backward compatibility, but we'll switch to `useNames = FALSE` soon, cf. https://github.com/HenrikBengtsson/matrixStats/issues/226.

The switch to `useNames = FALSE` will break **GenEst**.  I've created PR #656 that fixes this. All that was needed is to specify `useNames = TRUE` in `summary.splitFull()` in two places.

PS. I noticed that you submitted **GenEst** 1.4.7 to CRAN just two hours ago. What's the chance for that?  Oh, well.  If you happen to get a pushback on that submission, please consider incorporating this PR in your resubmission.

**Comment by ddalthorp** [comment]
Henrik, this is great.

Thanks for your help on suggestions for making GenEst work with the new matrixStats.

Your work goes above and beyond the call of duty.

Much appreciated.

-Dan
------- Original Message -------

**Comment by HenrikBengtsson** [comment]
I see a commit on this. Do you have an ETA for submitting this to CRAN?

**Comment by ddalthorp** [comment]
23 Nov 2022

------- Original Message -------

**Comment by HenrikBengtsson** [comment]
Oh, so your saying it's already on CRAN. I missed that because this issue was still open.
