### ISSUE TITLE
improve general app formatting

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#69]
everything is stylized with out-of-the-box style sheets
do we want a more customized style? there are a few theme options easily available through shiny (https://shiny.rstudio.com/gallery/shiny-theme-selector.html), and it is also possible (albeit much more time consuming) to get more hands-on with the style sheet.

**Comment by DAPPERstats** [comment]
@mhuso i didn't have a chance to mention this today, but take a look at those themes and let me know what your thoughts are!

**Comment by mhuso** [comment]
Interesting! At this point I don't have a strong preference away from default. It might change once we know what the banner will look like - some of these themes might work better with it than others. It looks like something that can be changed really easily, but I suppose we might need to be careful. Changing a theme (increased font for example) might cause some of our buttons to drop off the screen (require the user to scroll to see them). Do you have a preference?
