### ISSUE TITLE
sorting the model choice dropdowns

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#8]
we want to make the model choice dropdowns able to be sorted by AICc or whatever the use would like.

**Comment by DAPPERstats** [comment]
we should really talk about the capacity we'd like for this. the ability to sort by AIC and by name make sense. Is there anything else we want the user to be able to sort by?

**Comment by mhuso** [comment]
I'm not sure we need to make sorting a feature. I'm ok with providing the table sorted by Δ AICc without necessarily allowing user to sort by other things. I think this would make your coding easier, too. If others have strong opinions otherwise, I'm open....

**Comment by DAPPERstats** [comment]
model choice dropdowns for both SE and CP are now auto-sorted by AICc
