### ISSUE TITLE
include warnings for the number of observations per cell

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#86]
in the app

**Comment by DAPPERstats** [comment]
what are the basic rule of thumb guidelines for sample sizes for the se and cp models (@ddalthorp @madsenl @prabie )?

**Comment by ddalthorp** [comment]
"what are the basic rule of thumb guidelines for sample sizes for the se and cp models?"

Arbitrary. 

Manuela uses n = 10 per cell in DS729.

**Comment by DAPPERstats** [comment]
was done with a previous PR, not sure which one, but now in the app if you have fewer than 10 samples within a cell, you get a warning message
