### ISSUE TITLE
include more realistic example data sets

### ISSUE THREAD

**Issue by DAPPERstats** [ddalthorp/GenEst#91]

**Comment by ddalthorp** [comment]
I'm adapting some of my realistic example data sets for wind to match new data requirements. 

Paul's putting together a solar example.

**Comment by ddalthorp** [comment]
Actually, I was thinking it would make more sense to include them as .csv's...to serve as templates for users to enter their own data and as a common starting point for illustrating how to use the software (in, e.g., workshop, user guide, etc.).

**Comment by ddalthorp** [comment]
"Note that I've got a draft of the script"

Cool!

**Comment by DAPPERstats** [comment]
having them as csv's makes sense as well. i think having them in both formats is probably the best, as the .RData version is much better for the command line (including the examples, vignettes, etc) and links well with the roxygen2 documentation which allows for a thorough description/meta info. 

to keep things tight and consistent, I'd propose that each data set has the following:
 - `<datasetName>.RData` file, which is a list named `<datasetName>` that has elements named `data_SE`, `data_CP`, `data_SS` and `data_CO`. 
 - a folder located at `/inst/extdata/<datasetName>` with the csv files (one for each component dataset) and named `data_SE.csv`, `data_CP.csv`, `data_SS.csv` and `data_CO.csv`. 
 - a documentation entry in the `/R/data.R` script

A given full dataset doesn't need to have all of the components (SE, CP, SS, CO). For example, if we want to provide an example of a particularly gnarly CP analysis or something, we might only want/need a CP dataset. Similarly, a given dataset could have other components as well.

**Comment by ddalthorp** [comment]
I believe we are going with SS data file to look something like:
```
date         unit1  unit2   unit3
4/1/2018      1       1        1
4/4/2018      0       1        1
4/7/2018      1       1        0
```

and we'll need a dwp file something like this:
```
Unit    dwp_bat  dwp_s   dwp_m   dwp_l 
unit1     0.82    0.91    0.84   0.80
unit2     0.14    0.21    0.17   0.11
unit3     0.08    0.10    0.13   0.06
```
and we'll need a way to gracefully handle season boundary definitions. A natural place to put them would be as a parallel column (optional) in the SS data file.

```
date       season  unit1  unit2   unit3
4/1/2018     Sp      1       1        1
4/4/2018     Su      0       1        1
4/7/2018     Fa      1       1        0
```
format would be much like that of the other data files that include (optional) covariate columns along with the required data.

**Comment by DAPPERstats** [comment]
Got it. So then I think we can include the searches and covariates on the search as you have here in the `SearchData` components, and then also have an additional `DensityWeightedProportion` component?

**Comment by ddalthorp** [comment]
I'm not sure what your "component" is. We need .csv's for ss, dwp, cp, se, and co (inst/extdata). These read into data frames in R (/data/*.Rdata and in the app).

ss...column of dates and columns for each unit sampled. 0s and 1s to indicate which units were searched on which dates. Optional 'season' column.

dwp...array with one dwp for each unit (maybe in later version allow dwp to vary with date, but we need to test that model first)

cp and se...same format as they've always been

co...same format as it's always been EXCEPT date of carcass discovery is now required

The temporal 'season' covariate is different from covariates that are tied to space (e.g., visibility class) or carcasses (e.g., species). The spatial and carcass-specific covariate levels are attached to carcasses when they are discovered (hence, they belong in co). The season covariate level depends on the assumed arrival interval (simulated) for a carcass and is not assigned at time of carcass discovery but, rather, in the calculations of p(Oi | Aj) and is associated with arrival intervals. It seems easiest to tie the season to the search schedule. (An alternative would be to define the season boundaries in yet another [albeit simple] data file. This feels clumsier to me than including it as an option covariate of search interval.) ALL other covariates would be tied with discovered carcasses in the co file.

**Comment by DAPPERstats** [comment]
components as in component datasets as in 

> "a folder located at `/inst/extdata/<datasetName>` with the csv files (one for each **component** dataset) and named `SearcherEfficiencyData.csv`, `CarcassPersistenceData.csv`, `SearchData.csv` and `CarcassData.csv`."

>  "all of the **components** (SE, CP, SS, CO)"

so, yes, what you're talking about here. 

shouldn't the SS be rows of dates and columns of units?

the DWP data file doesn't need to be an array does it? it can be a flat .csv right?

**Comment by ddalthorp** [comment]
SS data file like this:
```
date       season  unit1  unit2   unit3
4/1/2018     Sp      1       1        1
4/4/2018     Sp      0       1        1
4/7/2018     Sp      1       1        0
7/1/2018     Su      1       1        1
7/8/2018     Su      1       1        0
9/3/2018     Fa      1       1        1
9/5/2018     Fa      1       1        1  
```
Surely the transpose would work as well, but this structure (with the season column) reads like a data frame and matches the CO file with dates running vertically and is almost identical to DS729. 

On another note, this data structure (whether as written or the transpose) is motivated by the demands of the model and not the needs of the search team entering the data. In future, we may want to allow a narrow structure as well (e.g., the template that Paul sent out last summer, with date column, single column for unit, column for season, and optional columns) from which the structure required by the model could be created after reading in the data.

dwp file to look like this:
```
Unit    dwp_bat  dwp_s   dwp_m   dwp_l 
unit1     0.82    0.91    0.84   0.80
unit2     0.14    0.21    0.17   0.11
unit3     0.08    0.10    0.13   0.06
```
An alternative would be to include additional rows for size-wise dwp's in the in the SS file. Or perhaps transpose the SS file (so dates run horizontally) and add additional columns for dwp and put the season on a row. This would break the data frame concept of having coherent columns, which we should try to avoid doing. Columns for, e.g., unit, bat, large, medium, and small (as above) is the simplest.

I don't see what you mean by a flat dwp file. We expect dwp to vary with both unit and carcass size, which lends itself naturally to a 2-d array.

If we open the door to dwp varying with date (which we may be able to do in the fairly near future), the structure will be more complicated.

**Comment by DAPPERstats** [comment]
ok, so yes then the rows are dates (you had written columns are dates and columns are units) in the ss file.

a flat csv as in a 2-d table, as in something that can be in a single .csv sheet without reference to other sheets. that is, not a relational dataset or a 3+ dimension table

i think we should enforce a particular structure within the model's guts, and if we want to have users be able to analyze different structural versions that we write some additional function to re-format the data to the needs of the model's guts. that's a much cleaner approach than trying to generalize the guts themselves to data that come in many different structures.

**Comment by ddalthorp** [comment]
"i think we should enforce a particular structure within the model's guts"

Absolutely. 

At this point, the input files for ss, co, dwp (as discussed above) closely match structures needed by the models. Later, we may add routines for parsing other .csv input formats into the structures the model needs.

**Comment by DAPPERstats** [comment]
note the example data set is now named `mockData` and is structured in the above-mentioned format. 

also, as of v 0.0.3.10, the app includes input capacity for the DWP data. there's still nothing happening with it aside from presentation (you can see the inputted data sheet), but the structure exists now.

**Comment by DAPPERstats** [comment]
@prabie checking in re: the solar data example

**Comment by ddalthorp** [comment]
I believe @mintzj was planning on finishing it (three examples) up today (5/18).

**Comment by DAPPERstats** [comment]
for the time being, i'd say we have this issue taken care of. there are now 2 solar and 3 wind data sets in addition to the mock one. plenty for the beta release, and we can consider adding specific data sets to address particular situations as they arise
