### ISSUE TITLE
Non crash error, Figures: Dim of X 

### ISSUE THREAD

**Issue by mintzj** [ddalthorp/GenEst#94]
This is an non-crash error which showed up in the Analyses > Searcher Efficiency > Figures panel.   I can produce this error in the following way: 

1. Load Searcher Efficiency Data File "ExampleSearcherEfficiency.csv" 
2. Analysis > General inputs: Iterations = 1000, Confidence Level = 0.9, Size Class = Size
3. Analysis > Searcher Efficiency: Observations = Search1
                                                     Predictor Variables = Visibility, Fix k = No
4. Run Searcher Efficiency Model
5. Analyses > Searcher Efficiency > Figures

![image](https://user-images.githubusercontent.com/11892333/38588952-4857b2b8-3cdd-11e8-890b-97d0bdcba8c5.png)

```Listening on http://127.0.0.1:4516
Only one observation, k cannot be estimated, fixed at 1
Only one observation, k cannot be estimated, fixed at 1
Only one observation, k cannot be estimated, fixed at 1
Only one observation, k cannot be estimated, fixed at 1
Warning: Error in apply: dim(X) must have a positive length
Stack trace (innermost first):
    104: apply
    103: pkmSetSpecSECellPlot
    102: plot.pkmSet
    101: plot
    100: renderPlot [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#363]
     90: <reactive:plotObj>
     79: plotObj
     78: origRenderFunc
     77: output$figSE
      2: shiny::runApp
      1: GenEst::runGenEst
```

Although this is a non-crash error, I thought this might be related to the error Dan submitted because it has to do with dimensions and his error is about subscripts being out of bounds.

**Comment by ddalthorp** [comment]
This looks like an instance of a difficult feature of R...vectors have NULL dimension, so when you write functions to accommodate matrix data, they can easily crash when what you intended to be an n x 1 (or 1 x n) array is read as a vector in R. This is a problem with 'apply' (as here) or with dim(x) or with x[ , i] or....

**Comment by mintzj** [comment]
"Object 'probs' not found".  An different non-crash bug, but it manifests itself in a similar way so I'm including it in this thread.   To reproduce, 
1. Load Carcass Persistence Data File "ExampleCarcassPersistence.csv"
2. Analysis > Carcass Persistence: Last Time Present = LastPresentDecimalDays
                                                      First Time Absent = FirstAbsentDecimalDays
                                                      Predictor Variables: Visibility*
                                                      Distributions to Include: (All)
3.  Run Carcass Persistence Model
4. Analyses > Carcass Persistence > Figures

* This will also occur if you choose other types of predictor variables (choosing only one).  May occur for other combinations of predictors as well.  Also occurred when "Size" and "Season" were used together as predictors.


![image](https://user-images.githubusercontent.com/11892333/38589449-df1f3b2e-3cdf-11e8-81d5-e2aada48f140.png)

```Listening on http://127.0.0.1:4516
No size class provided, function run as if pkmSet
Warning: Error in ppersist: object 'probs' not found
Stack trace (innermost first):
    105: ppersist
    104: t
    103: cpmSetSpecCPCellPlot
    102: plot.cpmSet
    101: plot
    100: renderPlot [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#737]
     90: <reactive:plotObj>
     79: plotObj
     78: origRenderFunc
     77: output$figCP
      2: shiny::runApp
      1: GenEst::runGenEst
```


If Size, Season, and Visibility are included as predictors, a crash will result.  Takes a minute or two to occur (model takes a while to run).

```Listening on http://127.0.0.1:4516
No size class provided, function run as if pkmSet
Models with incorrect specification were removed from output.
Warning: Error in $: $ operator is invalid for atomic vectors
Stack trace (innermost first):
    66: observeEventHandler [C:\Users\jmintz\Documents\R\win-library\3.4\GenEst\application\GenEst/server.R#461]
     2: shiny::runApp
     1: GenEst::runGenEst
ERROR: [on_request_read] connection reset by peer
```

**Comment by DAPPERstats** [comment]
in general, it's better to keep bugs to separate issues unless they're identical (same function, similar inputs, same output), so they can be addressed and closed one at a time

**Comment by DAPPERstats** [comment]
the probs issue is associated with a rename of the output for the loglogistic only in https://github.com/ddalthorp/GenEst/commit/becc8703992b9d0f19b7d15ca68711a389d5f0b8 
i'm changing the output name back to match the function's requirements for the output

**Comment by DAPPERstats** [comment]
both have been fixed through recent PRs (I've been patching and pushing a little at a time to test the install ability, so I'm not sure which PR #s to tag)
